# -*- coding: utf-8 -*-
"""「按处境找」的场景定义。

结构：场景名 → 所属分组 → 若干第一人称问句 → 每个问句对应 2-3 篇章节。
分组会渲染成首页的小标题：原先 76 个处境平铺，默认只露得出 4 个，
其余全折在「展开全部」后面——加多少处境用户都看不见。
场景名只说处境，不写问题；问题在点开之后才出现，答案挂在问题下面。
所有 (slug, k) 引用在构建时逐条校验，写错一个就构建失败。
"""

SCENES = [

# ── 决策 ──
("情绪上头", "要做决定", [
    ("这件事为什么让我这么难受？",
     [("epictetus", "judgments-not-things"), ("epictetus", "dichotomy")]),
    ("火已经上来了，怎么压住？",
     [("marcus-aurelius", "view-from-above"), ("su-shi", "no-wind-no-rain")]),
    ("话说出口才发现说错了。",
     [("liu-bang", "changing-mid-sentence"), ("zhang-yiming", "ordinary-mind")]),
    ("我对自己说话，比对谁都狠。",
     [("kristin-neff", "not-self-esteem"), ("kristin-neff", "three-parts")]),
    ("有些人我一见就烦，说不上为什么。",
     [("jung", "the-shadow"), ("adler", "separation-of-tasks")]),
]),
("做不完", "要做决定", [
    ("全都重要，我砍哪个都疼。",
     [("jobs", "focus-is-saying-no"), ("drucker", "right-things-first")]),
    ("我是不是在用忙掩盖不想面对的事？",
     [("wang-xing", "escape-from-thinking"), ("zeng-guofan", "self-watch")]),
    ("我在瞎忙，正事一件没动。",
     [("wang-xing", "escape-from-thinking"), ("drucker", "right-things-first")]),
    ("事情堆在一起，我不知道先动哪个。",
     [("mao", "on-contradiction"), ("influence", "social-proof")]),
]),
("起了冲突", "要做决定", [
    ("他明摆着有恶意，我还忍吗？",
     [("caesar", "clementia"), ("su-shi", "no-bad-people")]),
    ("我怕自己在气头上做错决定。",
     [("epictetus", "judgments-not-things"), ("zhang-liang", "picking-up-the-shoe")]),
    ("我一句话就把人得罪了。",
     [("analects", "reciprocity"), ("chris-voss", "thats-right")]),
    ("他给我难堪，我忍了这一次。",
     [("zhang-liang", "picking-up-the-shoe"), ("caesar", "clementia")]),
]),
("拖着不开始", "要做决定", [
    ("总想再准备准备，就是不开始。",
     [("paul-graham", "dont-scale"), ("boyd", "ooda")]),
    ("我知道该做，可就是动不了。",
     [("wang-yangming", "unity-of-knowing-and-doing"), ("franklin", "one-virtue-a-week")]),
    ("想等条件齐了再动，可它总不齐。",
     [("caesar", "the-rubicon"), ("mao", "strategy-of-the-revolution")]),
    ("我在等一个万全的时机。",
     [("caesar", "the-rubicon"), ("caesar", "clementia")]),
]),
("不可逆的决定", "要做决定", [
    ("这一步迈出去就收不回来了。",
     [("caesar", "the-rubicon"), ("xiang-yu", "sinking-the-boats")]),
    ("把退路堵死，是勇还是蠢？",
     [("schelling", "binding-yourself"), ("han-xin", "back-to-the-river")]),
    ("万一错了，我还有退路吗？",
     [("graham", "margin-of-safety"), ("li-ka-shing", "ninety-percent-failure")]),
    ("我想在动手前先确认能赢。",
     [("sun-tzu", "win-before-fighting"), ("mao", "strategy-of-the-revolution")]),
    ("机会比预想的大，我敢不敢加码。",
     [("su-yu", "enlarging-huaihai"), ("dalio", "believability")]),
    ("退路是该留着，还是该拿掉。",
     [("han-xin", "back-to-the-river"), ("han-xin", "neither-nor")]),
]),
("信息不全", "要做决定", [
    ("等数据齐了，还来得及吗？",
     [("boyd", "ooda"), ("grove", "inflection-and-cassandras")]),
    ("我凭什么相信自己这次的判断？",
     [("mao", "on-practice"), ("dalio", "believability")]),
    ("我是不是根本问错了问题？",
     [("einstein", "formulating-the-problem"), ("socrates", "midwifery")]),
    ("我对自己和对手都没底。",
     [("sun-tzu", "know-both"), ("guo-jia", "ten-victories")]),
    ("情况我根本没摸全，就得拍板。",
     [("records-of-the-grand-historian", "i-am-confused"), ("einstein", "formulating-the-problem")]),
    ("对手哪儿都比我强，怎么跟人打。",
     [("sun-tzu", "know-both"), ("guo-jia", "ten-victories")]),
]),
("方案被否", "要做决定", [
    ("方案被毙了，还提第二次吗？",
     [("su-yu", "daring-to-state"), ("li-shimin", "hearing-all-sides")]),
    ("我怕再提就成了顶撞领导。",
     [("zhang-liang", "borrowing-chopsticks"), ("strategies-of-the-warring-states", "three-mirrors")]),
    ("该坚持，还是该认这个否定？",
     [("boyd", "to-be-or-to-do"), ("thiel", "the-contrarian-question")]),
    ("我的方案被否了，还要不要争。",
     [("su-yu", "daring-to-state"), ("li-shimin", "the-first-debate")]),
]),
("全票通过", "要做决定", [
    ("所有人都同意，我反而心虚。",
     [("li-shimin", "the-first-debate"), ("marks", "second-level-thinking")]),
    ("没人反对，我反而不放心。",
     [("munger", "invert"), ("thiel", "the-contrarian-question")]),
    ("我是不是被会上的气氛带走了？",
     [("crowd", "descent-in-crowds"), ("influence", "social-proof")]),
    ("这个说法太顺了，我有点犯嘀咕。",
     [("popper", "falsifiability"), ("feynman", "dont-fool-yourself")]),
    ("我是不是把话说得太满了？",
     [("franklin", "never-say-certainly"), ("analects", "reciprocity")]),
    ("顺得不像话，我反倒不安。",
     [("munger", "invert"), ("munger", "latticework")]),
]),

# ── 竞争 ──
("对手更强", "有对手", [
    ("整体拼不过，我还有哪块能赢？",
     [("napoleon", "decisive-point"), ("sun-tzu", "form-like-water")]),
    ("速战速决，还是拖下去？",
     [("mao", "on-protracted-war"), ("sima-yi", "waiting")]),
    ("硬碰肯定输，我还有别的路吗？",
     [("sun-tzu", "win-without-fighting"), ("guan-zhong", "buying-deer")]),
    ("我习惯的那套打法，这次不管用。",
     [("musashi", "no-favorite-weapon"), ("huo-qubing", "no-old-manuals")]),
    ("对面比我强，我从哪里下手？",
     [("li-bi", "strike-the-base"), ("sima-yi", "eight-days")]),
]),
("被牵着走", "有对手", [
    ("他每出一招，我都得接吗？",
     [("zhang-yiming", "ordinary-mind"), ("wang-xing", "core-not-boundary")]),
    ("我一直在接招，节奏不在我手里。",
     [("boyd", "ooda"), ("sun-tzu", "orthodox-and-surprise")]),
    ("我盯着眼前，反而看丢了大局。",
     [("musashi", "two-ways-of-seeing"), ("huo-qubing", "feeding-off-the-enemy")]),
    ("我总在追着别人的节奏跑。",
     [("sima-yi", "eight-days"), ("guo-jia", "leave-the-baggage")]),
    ("我一直在接招，从没出过招。",
     [("sun-tzu", "orthodox-and-surprise"), ("musashi", "two-ways-of-seeing")]),
    ("补给和后勤把我拖住了。",
     [("huo-qubing", "feeding-off-the-enemy"), ("sun-tzu", "form-like-water")]),
]),
("进不进红海", "有对手", [
    ("这行早挤满了，我还进吗？",
     [("thiel", "competition-is-for-losers"), ("huang", "zero-billion-markets")]),
    ("别人跑在前面，我还来得及吗？",
     [("duan-yongping", "dare-to-be-last"), ("guo-jia", "waiting-out-liaodong")]),
    ("这行挤满了人，我还进吗？",
     [("thiel", "competition-is-for-losers"), ("naval", "assets-while-you-sleep")]),
    ("对手自己乱起来了，我要不要插一手。",
     [("guo-jia", "waiting-out-liaodong"), ("sima-yi", "waiting")]),
]),
("赢了之后", "有对手", [
    ("赢了，追下去还是收手？",
     [("art-of-worldly-wisdom", "quit-while-winning"), ("napoleon", "sublime-to-ridiculous")]),
    ("赢了这一把，要不要加码？",
     [("su-yu", "enlarging-huaihai"), ("bismarck", "art-of-the-possible")]),
    ("连着顺了几把，我怕栽跟头。",
     [("taleb", "turkey-problem"), ("buffett", "swimming-naked")]),
    ("赢是赢了，我不知道什么时候停。",
     [("napoleon", "sublime-to-ridiculous"), ("li-ka-shing", "knowing-when-to-stop")]),
    ("顺风顺水这么久，我心里发毛。",
     [("taleb", "turkey-problem"), ("buffett", "swimming-naked")]),
]),

# ── 钱 ──
("投资在亏", "钱的事", [
    ("亏着的这笔，砍还是扛？",
     [("livermore", "hope-and-fear-inverted"), ("soros", "knowing-when-wrong")]),
    ("是我看错了，还是还没到时候？",
     [("graham", "mr-market"), ("marks", "taking-the-temperature")]),
    ("我快扛不住了，还要不要扛？",
     [("lynch", "stomach-not-brain"), ("livermore", "sitting-tight")]),
    ("亏的时候我比赚的时候难受得多。",
     [("thinking-fast-and-slow", "loss-aversion"), ("taleb", "skin-in-the-game")]),
    ("看对了方向，我还是没拿住。",
     [("livermore", "sitting-tight"), ("lynch", "stomach-not-brain")]),
    ("跌成这样，我不知道该信谁。",
     [("graham", "mr-market"), ("livermore", "hope-and-fear-inverted")]),
]),
("该不该买", "钱的事", [
    ("买之前，我真的懂它吗？",
     [("buffett", "circle-of-competence"), ("munger", "latticework")]),
    ("这个价，算贵还是算便宜？",
     [("graham", "margin-of-safety"), ("marks", "taking-the-temperature")]),
    ("别人都在买，我跟不跟？",
     [("bai-gui", "take-what-others-drop"), ("technological-revolutions", "bubble-in-the-script")]),
    ("好东西就在眼前，我看得出吗？",
     [("lynch", "tenbagger-at-the-mall"), ("thinking-fast-and-slow", "loss-aversion")]),
    ("别人都说好，我就该跟吗？",
     [("lynch", "tenbagger-at-the-mall"), ("bai-gui", "take-what-others-drop")]),
]),
("怕错过", "钱的事", [
    ("这趟不上，是不是就没了？",
     [("soros", "reflexivity"), ("crowd", "assert-repeat-contaminate")]),
    ("这是真机会，还是击鼓传花？",
     [("technological-revolutions", "bubble-in-the-script"), ("marks", "second-level-thinking")]),
    ("所有人都在冲，我怕自己踏空。",
     [("soros", "reflexivity"), ("influence", "reciprocity")]),
]),
("让钱生钱", "钱的事", [
    ("钱放着不动，我心里发慌。",
     [("naval", "assets-while-you-sleep"), ("fan-li", "stock-the-opposite")]),
    ("我的收入完全绑在工时上。",
     [("naval", "productize-yourself"), ("wealth-of-nations", "pin-factory")]),
    ("我只会攒钱，不会让钱干活。",
     [("bai-gui", "four-qualifications"), ("inamori", "the-multiplier")]),
]),
("接不到活", "钱的事", [
    ("这个月没有单子，我开始慌了。",
     [("kevin-kelly", "thousand-true-fans"), ("paul-graham", "dont-scale")]),
    ("客户说走就走，我留不住人。",
     [("kevin-kelly", "direct-relationship"), ("influence", "reciprocity")]),
    ("手里就一个大客户，我睡不安稳。",
     [("graham", "margin-of-safety"), ("kevin-kelly", "thousand-true-fans")]),
    ("我一直在等活找上门。",
     [("paul-graham", "dont-scale"), ("kevin-kelly", "direct-relationship")]),
]),
("钱不够", "钱的事", [
    ("钱不够，我脑子一直乱着。",
     [("scarcity", "bandwidth-tax"), ("scarcity", "tunneling")]),
    ("越缺钱，我越容易做错决定。",
     [("scarcity", "bandwidth-tax"), ("graham", "margin-of-safety")]),
    ("眼前的事压着，我顾不上长远。",
     [("scarcity", "tunneling"), ("li-ka-shing", "knowing-when-to-stop")]),
    ("背着贷款，我每个月都紧巴巴。",
     [("paul-graham", "default-alive"), ("scarcity", "tunneling")]),
    ("这笔钱还不上了，我瞒着家里。",
     [("hu-xueyan", "the-silk-corner"), ("li-ka-shing", "ninety-percent-failure")]),
    ("同龄人都买房了，就我还在租。",
     [("bai-gui", "take-what-others-drop"), ("scarcity", "bandwidth-tax")]),
    ("没了收入，我不知道能撑多久。",
     [("paul-graham", "default-alive"), ("ren-zhengfei", "huaweis-winter")]),
    ("家里为钱吵，我们越吵越远。",
     [("hochschild", "second-shift"), ("nonviolent-communication", "needs-behind-blame")]),
    ("收入断了，我先该干什么。",
     [("su-shi", "east-slope"), ("paul-graham", "default-alive")]),
]),

# ── 人 ──
("这人可信吗", "跟人打交道", [
    ("第一次打交道，我看什么最准？",
     [("analects", "see-how"), ("zeng-guofan", "recruit-and-test")]),
    ("有本事但我信不过，用不用？",
     [("zizhi-tongjian", "talent-and-virtue"), ("cao-cao", "talent-only")]),
    ("他说得挺好，我有点不敢全信。",
     [("guiguzi", "sound-out"), ("han-feizi", "form-and-name")]),
    ("这人有才，但我摸不透他。",
     [("bai-gui", "four-qualifications"), ("la-rochefoucauld", "vice-pays-tribute")]),
    ("他说得漂亮，我还没见他做过。",
     [("han-feizi", "form-and-name"), ("analects", "see-how")]),
    ("简历很好看，可我还是拿不准。",
     [("zeng-guofan", "recruit-and-test"), ("zizhi-tongjian", "talent-and-virtue")]),
]),
("上面说的话不能信", "跟人打交道", [
    ("画的饼我已经不信了。",
     [("han-feizi", "form-and-name"), ("hu-xueyan", "no-cheating")]),
    ("答应我的事，一次次落空。",
     [("han-feizi", "form-and-name"), ("schelling", "binding-yourself")]),
    ("我还要不要接着信他。",
     [("analects", "see-how"), ("konnikova", "not-manufacturing-trust")]),
]),
("要说服人", "跟人打交道", [
    ("我说了不算，得让他自己想到。",
     [("guiguzi", "listen-in-reverse"), ("socrates", "midwifery")]),
    ("道理都讲完了，还是没用。",
     [("wealth-of-nations", "not-benevolence"), ("influence", "reciprocity")]),
    ("他从一开始就不认同我。",
     [("mandela", "springbok-jersey"), ("analects", "harmony-not-sameness")]),
    ("我一个人去谈，能谈得下来吗？",
     [("guo-ziyi", "riding-out-alone"), ("wu-zetian", "the-manifesto")]),
    ("我说的都对，可他就是不听。",
     [("guiguzi", "listen-in-reverse"), ("analects", "know-what-you-know")]),
    ("对面人多势众，我只有一张嘴。",
     [("guo-ziyi", "riding-out-alone"), ("wu-zetian", "the-manifesto")]),
]),
("谈条件", "跟人打交道", [
    ("我说的话，他们好像不太当真。",
     [("schelling", "binding-yourself"), ("shang-yang", "moving-the-pole")]),
    ("谈僵了，谁都不肯先动。",
     [("schelling", "focal-points"), ("guiguzi", "open-and-close")]),
    ("我该先让一步换个长远？",
     [("strategies-of-the-warring-states", "burning-the-debts"), ("taleb", "skin-in-the-game")]),
    ("没法商量，我只能猜他会怎么走。",
     [("schelling", "focal-points"), ("crowd", "assert-repeat-contaminate")]),
    ("眼前这笔我亏了，值不值得。",
     [("strategies-of-the-warring-states", "burning-the-debts"), ("guiguzi", "open-and-close")]),
]),
("被猜忌", "跟人打交道", [
    ("越解释越像心虚，说还是不说？",
     [("guo-ziyi", "open-gates"), ("wang-jian", "asking-for-fields")]),
    ("功劳太大，我反而开始不安。",
     [("fan-li", "leave-at-the-top"), ("han-xin", "neither-nor")]),
    ("我越做越好，上面反而防着我。",
     [("wang-jian", "asking-for-fields"), ("han-xin", "neither-nor")]),
]),

# ── 团队 ──
("错反复犯", "带人", [
    ("同一个坑，我们又掉进去了。",
     [("thinking-in-systems", "structure-drives-behavior"), ("han-feizi", "not-counting-on-goodness")]),
    ("问题一堆，我先动哪一处？",
     [("thinking-in-systems", "leverage-points"), ("zhang-juzheng", "kaocheng")]),
    ("复盘写了，下次还是照样犯。",
     [("records-of-the-grand-historian", "no-praise-no-hiding"), ("hu-xueyan", "the-silk-corner")]),
    ("同样的教训我怎么才记得住？",
     [("zizhi-tongjian", "what-to-keep"), ("franklin", "never-say-certainly")]),
    ("换了一批人，同样的错还在犯。",
     [("thinking-in-systems", "structure-drives-behavior"), ("han-feizi", "not-counting-on-goodness")]),
    ("我布置下去的事，没人当回事。",
     [("zhang-juzheng", "kaocheng"), ("mao", "methods-of-work")]),
]),
("下不了手", "带人", [
    ("该罚的是跟我最久的人。",
     [("zhuge-liang", "executing-ma-su"), ("shang-yang", "law-above-rank")]),
    ("要砍的是我亲手做起来的。",
     [("grove", "revolving-door"), ("huang", "strategic-retreat")]),
    ("要让人怕我，还是让人服我？",
     [("machiavelli", "feared-not-hated"), ("bismarck", "iron-and-blood")]),
    ("该罚的是我最看重的那个人。",
     [("zhuge-liang", "executing-ma-su"), ("shang-yang", "law-above-rank")]),
]),
("团队没劲", "带人", [
    ("我说了很多遍，团队还是没劲。",
     [("ren-zhengfei", "sound-of-gunfire"), ("inamori", "the-multiplier")]),
    ("奖也发了罚也罚了，好像没用。",
     [("han-feizi", "two-handles"), ("cao-cao", "burning-the-letters")]),
    ("我的人只是照做，没人真的上心。",
     [("mencius", "people-first"), ("hu-xueyan", "no-cheating")]),
    ("我该怎么带才不打击人？",
     [("vygotsky", "scaffolding"), ("dweck", "praise-the-process")]),
    ("我的人吃不饱，谈什么理想。",
     [("guan-zhong", "granaries-first"), ("cao-cao", "military-farming")]),
]),
("招人换人", "带人", [
    ("招个比我强的，我压得住吗？",
     [("liu-bang", "three-i-cannot"), ("simons", "simons-principles")]),
    ("想破格提一个人，又怕压不住。",
     [("wu-zetian", "promote-and-drop"), ("zhuge-liang", "close-the-worthy")]),
    ("这人能力强，人品我看不透。",
     [("cao-cao", "talent-only"), ("guiguzi", "sound-out")]),
    ("我提的人不行，换还是再等等。",
     [("wu-zetian", "promote-and-drop"), ("zhuge-liang", "close-the-worthy")]),
]),
("听不到实话", "带人", [
    ("汇报都很好，我却总觉得不对。",
     [("grove", "inflection-and-cassandras"), ("li-shimin", "hearing-all-sides")]),
    ("上次说真话的人，后来怎样了？",
     [("mao", "methods-of-work"), ("li-shimin", "boat-and-water")]),
    ("我听到的答应，其实没当真。",
     [("chris-voss", "thats-right"), ("liu-bang", "changing-mid-sentence")]),
    ("身边人说的都是我爱听的。",
     [("strategies-of-the-warring-states", "three-mirrors"), ("li-shimin", "boat-and-water")]),
]),
("队伍出不了活", "带人", [
    ("我带的这摊子，一直做不出成绩。",
     [("liu-bang", "three-i-cannot"), ("zeng-guofan", "recruit-and-test")]),
    ("布置下去的事，交上来总是走样。",
     [("zhang-juzheng", "kaocheng"), ("han-feizi", "form-and-name")]),
    ("我什么都自己上，越管越累。",
     [("liu-bang", "three-i-cannot"), ("zhuge-liang", "close-the-worthy")]),
    ("人不差，可就是拧不成一股。",
     [("xunzi", "division-makes-groups"), ("zeng-guofan", "solid-camp-dull-fight")]),
]),

# ── 做事 ──
("从零开始", "把事做成", [
    ("第一步做大还是先试小的？",
     [("paul-graham", "dont-scale"), ("zhu-yuanzhang", "delay-the-title")]),
    ("投进去之前，我怎么知道值不值？",
     [("drucker", "create-a-customer"), ("duan-yongping", "right-things-done-right")]),
    ("多久看不到结果，我就该停？",
     [("paul-graham", "default-alive"), ("zhang-yiming", "delayed-gratification")]),
    ("我现在这一步，往后看得清吗？",
     [("jobs", "connecting-the-dots"), ("einstein", "patent-office")]),
    ("我连自己能撑多久都算不出来。",
     [("paul-graham", "default-alive"), ("li-ka-shing", "ninety-percent-failure")]),
    ("别人都在抢先，我要不要慢一步。",
     [("zhu-yuanzhang", "delay-the-title"), ("duan-yongping", "dare-to-be-last")]),
    ("我想辞了自己干，可就是不敢。",
     [("paul-graham", "default-alive"), ("caesar", "the-rubicon")]),
    ("想去创业，可我不敢辞。",
     [("paul-graham", "default-alive"), ("caesar", "the-rubicon")]),
]),
("推不动", "把事做成", [
    ("推了很久推不动，该换方向吗？",
     [("on-war", "friction"), ("mao", "on-contradiction")]),
    ("只剩笨办法了，还要不要做？",
     [("zeng-guofan", "solid-camp-dull-fight"), ("bruce-lee", "one-kick")]),
    ("一改就出乱子，不改又不行。",
     [("old-regime", "most-dangerous-moment"), ("old-regime", "centralization-survived")]),
    ("我以为规划得够细了。",
     [("hayek", "fatal-conceit"), ("why-nations-fail", "fear-of-creative-destruction")]),
    ("别人的成功打法，我照搬不动。",
     [("huo-qubing", "no-old-manuals"), ("musashi", "no-favorite-weapon")]),
    ("计划挺好，落到地上就走样。",
     [("on-war", "friction"), ("zeng-guofan", "solid-camp-dull-fight")]),
]),
("扩不扩张", "把事做成", [
    ("什么该做什么不做，我拿不准。",
     [("wang-xing", "core-not-boundary"), ("bezos", "what-wont-change")]),
    ("摊子越铺越大，我有点怕。",
     [("wang-jian", "sixty-thousand"), ("innovators-dilemma", "small-markets")]),
    ("摊子铺开，我拿什么养住？",
     [("cao-cao", "military-farming"), ("guo-jia", "leave-the-baggage")]),
    ("这块太小了，值得我进吗？",
     [("innovators-dilemma", "small-markets"), ("huang", "zero-billion-markets")]),
]),
("成本降不动", "把事做成", [
    ("该降的都降了，还能从哪下刀？",
     [("musk", "idiot-index"), ("musk", "first-principles")]),
    ("我降到多少，局面才会变？",
     [("matsushita", "tap-water"), ("wealth-of-nations", "pin-factory")]),
    ("这个成本压不下去，我卡住了。",
     [("musk", "first-principles"), ("xunzi", "borrow-from-things")]),
]),
("顺境里发慌", "把事做成", [
    ("日子正好，我该准备什么？",
     [("ren-zhengfei", "huaweis-winter"), ("fan-li", "stock-the-opposite")]),
    ("我们最强的地方，会不会正是死穴？",
     [("innovators-dilemma", "good-management-fails"), ("bezos", "day-one")]),
    ("摊子铺得太快，我心里没底。",
     [("hu-xueyan", "the-silk-corner"), ("old-regime", "most-dangerous-moment")]),
    ("行情好的时候我该干什么？",
     [("matsushita", "umbrella-in-rain"), ("tao-te-ching", "water")]),
    ("现在一切都好，我反而睡不着。",
     [("ren-zhengfei", "huaweis-winter"), ("bezos", "day-one")]),
    ("赚钱太顺，我怕自己看不见风险。",
     [("tao-te-ching", "reversal"), ("art-of-worldly-wisdom", "quit-while-winning")]),
]),
("做的东西没人看", "把事做成", [
    ("发出去没人看，我还写不写。",
     [("murakami", "no-one-asked-you-to"), ("kevin-kelly", "thousand-true-fans")]),
    ("我坐在那儿一个字也写不出来。",
     [("murakami", "stop-while-it-flows"), ("murakami", "focus-and-endurance")]),
    ("我是不是根本没这个天赋。",
     [("murakami", "focus-and-endurance"), ("dweck", "praise-the-process")]),
    ("开头总是有劲，后面就断了。",
     [("murakami", "stop-while-it-flows"), ("bj-fogg", "tiny-habits")]),
    ("我做的东西越来越像别人的。",
     [("murakami", "no-one-asked-you-to"), ("thiel", "competition-is-for-losers")]),
]),

# ── 自己 ──
("在低谷", "自己的状态", [
    ("这段日子，到底熬来了什么？",
     [("frankl", "the-last-freedom"), ("nietzsche", "what-does-not-kill")]),
    ("这次栽了，我能捡回点什么？",
     [("dalio", "pain-plus-reflection"), ("su-shi", "three-exiles")]),
    ("最难的时候，还剩什么是我的？",
     [("marcus-aurelius", "obstacle-is-the-way"), ("frankl", "happiness-ensues")]),
    ("这件事我到现在都没想明白。",
     [("records-of-the-grand-historian", "i-am-confused"), ("mencius", "flood-like-qi")]),
    ("我这段没人看见的日子有用吗？",
     [("einstein", "patent-office"), ("jobs", "connecting-the-dots")]),
    ("撑不下去的时候，我对自己特别狠。",
     [("kristin-neff", "not-self-esteem"), ("brene-brown", "guilt-not-shame")]),
    ("我谁也不想见，可又难受。",
     [("cacioppo", "loneliness-is-a-signal"), ("kristin-neff", "three-parts")]),
]),
("想太多", "自己的状态", [
    ("这事在我脑子里转了二十遍。",
     [("marcus-aurelius", "morning-preparation"), ("epictetus", "dichotomy")]),
    ("我一直在想我改变不了的事。",
     [("wang-yangming", "polish-on-things"), ("huineng", "originally-not-a-thing")]),
    ("我怕自己越斗越像对手。",
     [("nietzsche", "gazing-into-abyss"), ("bismarck", "iron-and-blood")]),
    ("外面太吵，我静不下来。",
     [("matsushita", "umbrella-in-rain"), ("marcus-aurelius", "morning-preparation")]),
    ("跟烂事纠缠久了，我也变得难看。",
     [("zhuangzi", "ox-carving"), ("tao-te-ching", "water")]),
    ("我脑子里一直在骂自己。",
     [("brene-brown", "guilt-not-shame"), ("wang-yangming", "bandits-in-the-heart")]),
]),
("知道做不到", "自己的状态", [
    ("道理都懂，可我就是不动。",
     [("wang-yangming", "unity-of-knowing-and-doing"), ("wang-yangming", "bandits-in-the-heart")]),
    ("这个毛病我改了很多次了。",
     [("franklin", "one-virtue-a-week"), ("bruce-lee", "one-kick")]),
    ("练了很久，感觉没什么长进。",
     [("ericsson", "deliberate-practice"), ("ericsson", "not-ten-thousand-hours")]),
    ("道理我都懂，就是做不到。",
     [("bj-fogg", "tiny-habits"), ("dweck", "praise-the-process")]),
    ("书看了不少，用的时候想不起来。",
     [("feynman", "teach-to-understand"), ("bruce-lee", "be-water")]),
    ("道理我都懂，可我做不到。",
     [("popper", "falsifiability"), ("dweck", "effect-size")]),
]),
("学不进去", "自己的状态", [
    ("看了很多，一到用就想不起来。",
     [("mao", "on-practice"), ("wang-yangming", "polish-on-things")]),
    ("我不懂，但不好意思说。",
     [("analects", "know-what-you-know"), ("socrates", "knowing-not-knowing")]),
    ("我是不是一直在用笨办法学？",
     [("xunzi", "borrow-from-things"), ("munger", "latticework")]),
    ("我以为懂了，一讲就卡壳。",
     [("feynman", "teach-to-understand"), ("ericsson", "deliberate-practice")]),
    ("练了很多遍，还是不熟。",
     [("vygotsky", "zpd"), ("vygotsky", "scaffolding")]),
    ("我学的东西太死板了。",
     [("bruce-lee", "be-water"), ("huineng", "in-the-world")]),
]),
("忙到没自己", "自己的状态", [
    ("日程排满了，没一件是我自己的。",
     [("tao-te-ching", "usefulness-of-emptiness"), ("zhuangzi", "use-of-uselessness")]),
    ("同样的事，我总比别人费劲。",
     [("zhuangzi", "ox-carving"), ("tao-te-ching", "wu-wei")]),
    ("一天没干成什么，我却累得说不出话。",
     [("hochschild", "emotional-labor"), ("cal-newport", "attention-residue")]),
    ("拼了这几年，朋友一个个断了。",
     [("harvard-study", "relationships-predict-health"), ("harvard-study", "social-fitness")]),
]),
("被比下去", "自己的状态", [
    ("他什么都比我快一步。",
     [("zhuangzi", "equalizing-things"), ("la-rochefoucauld", "memory-vs-judgment")]),
    ("我到底在证明自己，还是在做事？",
     [("boyd", "to-be-or-to-do"), ("xiang-yu", "brocade-at-night")]),
    ("我是不是天生就不如人？",
     [("dweck", "praise-the-process"), ("dweck", "effect-size")]),
    ("他们看起来都很稳，只有我在慌。",
     [("brene-brown", "secrecy-silence-judgment"), ("socrates", "knowing-not-knowing")]),
    ("道理都懂，我就是对自己客气不起来。",
     [("kristin-neff", "three-parts"), ("carl-rogers", "unconditional-regard")]),
]),
("不想卷但怕掉队", "自己的状态", [
    ("我不想卷，可又怕被落下。",
     [("zhuangzi", "use-of-uselessness"), ("buffett", "circle-of-competence")]),
    ("大家都在加班，我先走心虚。",
     [("analects", "harmony-not-sameness"), ("zhuangzi", "equalizing-things")]),
    ("拼了这么久，我不知道图什么。",
     [("frankl", "happiness-ensues"), ("wang-xing", "escape-from-thinking")]),
    ("光靠拼命，我拼不过他们。",
     [("xunzi", "borrow-from-things"), ("naval", "productize-yourself")]),
]),

# ── 位置 ──
("该不该接", "进退取舍", [
    ("位置给我了，我看不清风险在哪。",
     [("li-bi", "no-office"), ("feng-dao", "only-you-can-save")]),
    ("机会挺好，就怕我接不住。",
     [("wang-jian", "sixty-thousand"), ("inamori", "pure-motive")]),
    ("这个位置我接下来，可能是个坑。",
     [("zhuge-liang", "longzhong-plan"), ("hayek", "knowledge-is-dispersed")]),
    ("刚接手，我第一条规矩该立什么。",
     [("liu-bang", "three-articles"), ("xunzi", "origin-of-rites")]),
    ("接之前，我该先说清哪一块。",
     [("zhuge-liang", "longzhong-plan"), ("zhuge-liang", "close-the-worthy")]),
]),
("该不该退", "进退取舍", [
    ("我该什么时候退，才不难看？",
     [("fan-li", "leave-at-the-top"), ("li-ka-shing", "knowing-when-to-stop")]),
    ("我交出去之后，会不会一团糟？",
     [("lee-kuan-yew", "from-my-sickbed"), ("zhang-liang", "asking-for-less")]),
    ("我这一路的取舍，怎么交代？",
     [("feng-dao", "the-long-happy-old-man"), ("hayek", "fatal-conceit")]),
    ("该收手了，可我停不下来。",
     [("lee-kuan-yew", "from-my-sickbed"), ("feng-dao", "only-you-can-save")]),
]),
("要立规矩", "进退取舍", [
    ("新规矩定了，没人当回事。",
     [("shang-yang", "moving-the-pole"), ("liu-bang", "three-articles")]),
    ("松了没用，紧了怕逼走人。",
     [("zhu-yuanzhang", "heavy-law"), ("guan-zhong", "follow-the-people")]),
    ("我压得住人，却服不了人。",
     [("mencius", "force-vs-virtue"), ("mencius", "people-first")]),
    ("规矩定了，怎么才落得下去？",
     [("zhang-juzheng", "single-whip"), ("xunzi", "origin-of-rites")]),
    ("我为什么非得立规矩？",
     [("xunzi", "division-makes-groups"), ("guan-zhong", "granaries-first")]),
    ("规矩太多太乱，我自己都记不住。",
     [("zhang-juzheng", "single-whip"), ("xunzi", "division-makes-groups")]),
]),
("看不清大势", "进退取舍", [
    ("现在到底是开头还是快结束了？",
     [("marks", "taking-the-temperature"), ("technological-revolutions", "bubble-in-the-script")]),
    ("十年之后，哪些还站得住？",
     [("bezos", "what-wont-change"), ("sovereign-individual", "logic-of-violence")]),
    ("同样的条件，我们差在哪？",
     [("why-nations-fail", "two-nogales"), ("hayek", "knowledge-is-dispersed")]),
    ("我看不出这局面是怎么形成的。",
     [("guns-germs-steel", "axis-of-continents"), ("sapiens", "fictions-that-cooperate")]),
    ("大家都这么做，可我说不出为什么。",
     [("sapiens", "wheat-domesticated-us"), ("mencius", "force-vs-virtue")]),
    ("我看不出下一步棋该往哪走。",
     [("zhuge-liang", "longzhong-plan"), ("li-bi", "strike-the-base")]),
]),

# ── AI 来了 ──
# 门牌用今天的词，答案全指向现成的章节——内容层照旧不过期。
# 这阵过去了，退掉这一组很便宜；退章节才贵。
("我这行会不会没了", "AI 来了", [
    ("我这行是不是快没了。",
     [("taleb", "turkey-problem"), ("technological-revolutions", "bubble-in-the-script")]),
    ("现在好好的，我怕的是往后。",
     [("taleb", "turkey-problem"), ("fan-li", "stock-the-opposite")]),
    ("行业还在，可我这个岗位没了。",
     [("innovators-dilemma", "good-management-fails"), ("fan-li", "stock-the-opposite")]),
    ("公司照老样子做，我看着悬。",
     [("innovators-dilemma", "good-management-fails"), ("taleb", "turkey-problem")]),
]),
("追不上新东西", "AI 来了", [
    ("东西一天一个样，我追不上。",
     [("bruce-lee", "one-kick"), ("csikszentmihalyi", "flow-channel")]),
    ("学了就忘，我不知道该练什么。",
     [("bruce-lee", "one-kick"), ("feynman", "teach-to-understand")]),
    ("太难我慌，太简单又没长进。",
     [("csikszentmihalyi", "flow-channel"), ("bruce-lee", "one-kick")]),
]),
("手艺不值钱了", "AI 来了", [
    ("练了十年的手艺，我现在不值钱了。",
     [("naval", "productize-yourself"), ("duan-yongping", "dare-to-be-last")]),
    ("机器几秒做完我一天的活。",
     [("naval", "productize-yourself"), ("kevin-kelly", "direct-relationship")]),
    ("客户越过我，直接用工具了。",
     [("kevin-kelly", "direct-relationship"), ("naval", "productize-yourself")]),
]),
("工具替我想了", "AI 来了", [
    ("什么都问它，我自己不会想了。",
     [("vygotsky", "scaffolding"), ("feynman", "teach-to-understand")]),
    ("交出去的东西，我讲不明白。",
     [("feynman", "teach-to-understand"), ("vygotsky", "scaffolding")]),
    ("离了工具，我就不敢下笔了。",
     [("vygotsky", "scaffolding"), ("bruce-lee", "one-kick")]),
]),
("出得多了人却空了", "AI 来了", [
    ("东西出得比以前多，我却更空。",
     [("drucker", "right-things-first"), ("zhuangzi", "use-of-uselessness")]),
    ("效率高了，做的还是没用的事。",
     [("drucker", "right-things-first"), ("csikszentmihalyi", "flow-channel")]),
]),
("人人都在喊风口", "AI 来了", [
    ("所有人都说这是风口，我慌。",
     [("crowd", "assert-repeat-contaminate"), ("soros", "reflexivity")]),
    ("越涨我越怕，越怕越想追。",
     [("soros", "reflexivity"), ("technological-revolutions", "bubble-in-the-script")]),
    ("这轮是真的，还是又一次。",
     [("technological-revolutions", "bubble-in-the-script"), ("crowd", "assert-repeat-contaminate")]),
]),
("要不要现在跳进去", "AI 来了", [
    ("我该现在冲，还是再等等。",
     [("duan-yongping", "dare-to-be-last"), ("fan-li", "stock-the-opposite")]),
    ("这块现在太小，我进不进。",
     [("huang", "zero-billion-markets"), ("duan-yongping", "dare-to-be-last")]),
    ("别人都抢先了，我还来得及吗。",
     [("duan-yongping", "dare-to-be-last"), ("huang", "zero-billion-markets")]),
]),
("日子被工具占满", "AI 来了", [
    ("我一天被消息切得七零八落。",
     [("cal-newport", "attention-residue"), ("finite-and-infinite-games", "two-kinds")]),
    ("我停不下来，怕一停就落后。",
     [("finite-and-infinite-games", "two-kinds"), ("cal-newport", "attention-residue")]),
]),
("不知道该练什么了", "AI 来了", [
    ("标准天天变，我不知道练什么。",
     [("excellent-sheep", "hurdles"), ("sapiens", "wheat-domesticated-us")]),
    ("过去管用的那套，现在不算数了。",
     [("sapiens", "wheat-domesticated-us"), ("excellent-sheep", "hurdles")]),
    ("越有用的活，越先被替掉了。",
     [("zhuangzi", "use-of-uselessness"), ("excellent-sheep", "hurdles")]),
]),
# ── 本轮新增：补上原先完全没有覆盖的处境 ──
("两个都想要", "跟人打交道", [
    ("两个我都想要，可只能选一个。",
     [("jobs", "focus-is-saying-no"), ("munger", "invert")]),
    ("看着都好，我到底适合哪个？",
     [("buffett", "circle-of-competence"), ("duan-yongping", "right-things-done-right")]),
    ("我到底为什么要打这一仗？",
     [("on-war", "continuation-of-politics"), ("sun-tzu", "win-before-fighting")]),
    ("砍掉的那个也是好主意，我舍不得。",
     [("jobs", "focus-is-saying-no"), ("jobs", "connecting-the-dots")]),
]),
("信不信直觉", "跟人打交道", [
    ("直觉和数据打架，我听哪个？",
     [("thinking-fast-and-slow", "wysiati"), ("simons", "slave-to-the-model")]),
    ("这次的直觉，我信得过吗？",
     [("simons", "simons-principles"), ("wang-yangming", "innate-knowing")]),
    ("我查的资料全都在支持我。",
     [("popper", "seek-refutation"), ("feynman", "dont-fool-yourself")]),
    ("我死活不肯承认这次买错了。",
     [("soros", "knowing-when-wrong"), ("simons", "slave-to-the-model")]),
    ("我这一眼看过去，就是觉得不对。",
     [("thinking-fast-and-slow", "wysiati"), ("popper", "seek-refutation")]),
]),
("定不好价", "跟人打交道", [
    ("东西是好东西，可就是卖不动。",
     [("wealth-of-nations", "not-benevolence"), ("drucker", "create-a-customer")]),
    ("我定多少钱，人才愿意掏？",
     [("matsushita", "tap-water"), ("musk", "idiot-index")]),
    ("我不知道该收多少钱。",
     [("kevin-kelly", "thousand-true-fans"), ("naval", "productize-yourself")]),
    ("我按工时收，越做越不值钱。",
     [("naval", "productize-yourself"), ("naval", "assets-while-you-sleep")]),
]),
("遇上不讲理", "跟人打交道", [
    ("我跟他讲道理，完全没用。",
     [("epictetus", "dichotomy"), ("machiavelli", "as-it-is")]),
    ("我要不要照他的路数回敬？",
     [("gandhi", "means-are-seeds"), ("su-shi", "no-bad-people")]),
    ("对方来势很硬，我硬碰吗？",
     [("gandhi", "salt-march"), ("machiavelli", "feared-not-hated")]),
    ("对方根本不跟我讲道理。",
     [("gandhi", "salt-march"), ("crowd", "descent-in-crowds")]),
]),
("功劳被抢", "跟人打交道", [
    ("事是我做的，功是别人的。",
     [("art-of-worldly-wisdom", "do-and-be-seen"), ("xiang-yu", "brocade-at-night")]),
    ("这个功，我要不要去争？",
     [("zhang-liang", "asking-for-less"), ("guo-ziyi", "open-gates")]),
    ("活是我干的，功劳记在别人头上。",
     [("la-rochefoucauld", "memory-vs-judgment"), ("art-of-worldly-wisdom", "do-and-be-seen")]),
]),
("该不该妥协", "跟人打交道", [
    ("退这一步，是务实还是没底线？",
     [("bismarck", "art-of-the-possible"), ("lee-kuan-yew", "does-it-work")]),
    ("手段脏了，目的还干净吗？",
     [("gandhi", "means-are-seeds"), ("machiavelli", "as-it-is")]),
    ("对方有诚意，我怎么判断？",
     [("taleb", "skin-in-the-game"), ("la-rochefoucauld", "vice-pays-tribute")]),
    ("道理站在我这边，可事办不成。",
     [("lee-kuan-yew", "does-it-work"), ("analects", "harmony-not-sameness")]),
]),
("总在讨好别人", "跟人打交道", [
    ("我总顺着别人，回头就难受。",
     [("satir", "coping-stances"), ("adler", "separation-of-tasks")]),
    ("我不会拒绝，答应完就后悔。",
     [("jobs", "focus-is-saying-no"), ("thomas-gordon", "problem-ownership")]),
    ("别人一不高兴，我就觉得是我的错。",
     [("satir", "coping-stances"), ("brene-brown", "guilt-not-shame")]),
    ("我想说不，可话到嘴边就软了。",
     [("jobs", "focus-is-saying-no"), ("satir", "iceberg")]),
]),
("推不动别人", "跟人打交道", [
    ("别的部门就是不配合我。",
     [("thinking-in-systems", "leverage-points"), ("ren-zhengfei", "sound-of-gunfire")]),
    ("我没有权力，还怎么推动事？",
     [("li-bi", "no-office"), ("zhang-liang", "borrowing-chopsticks")]),
    ("我上面的人明摆着不想变。",
     [("why-nations-fail", "fear-of-creative-destruction"), ("sovereign-individual", "citizen-to-customer")]),
    ("这摊子太烂，我该下重手吗？",
     [("zhu-yuanzhang", "heavy-law"), ("guan-zhong", "follow-the-people")]),
    ("我一直在骂人，可事没变。",
     [("thinking-in-systems", "structure-drives-behavior"), ("thinking-in-systems", "leverage-points")]),
]),
("合伙人闹掰", "跟人打交道", [
    ("分钱这事，我怕埋雷。",
     [("zhang-liang", "asking-for-less"), ("han-feizi", "two-handles")]),
    ("话都说绝了，还修得回来吗？",
     [("cao-cao", "burning-the-letters"), ("mandela", "springbok-jersey")]),
    ("当初没写清楚，现在我们各说各的。",
     [("han-feizi", "form-and-name"), ("liu-bang", "three-articles")]),
    ("我想散伙，可事还得做下去。",
     [("li-ka-shing", "knowing-when-to-stop"), ("han-xin", "neither-nor")]),
]),
("觉得没意义", "跟人打交道", [
    ("每天都一样，我不知道图什么。",
     [("frankl", "happiness-ensues"), ("zhuangzi", "use-of-uselessness")]),
    ("我做这些，到底为了什么？",
     [("inamori", "pure-motive"), ("frankl", "the-last-freedom")]),
    ("赢了这一局，然后呢？",
     [("finite-and-infinite-games", "two-kinds"), ("finite-and-infinite-games", "playing-with-boundaries")]),
    ("样样都做得不错，我却不知道要什么。",
     [("excellent-sheep", "hurdles"), ("excellent-sheep", "no-scoreboard")]),
    ("我非得离开这日子才能修行？",
     [("huineng", "in-the-world"), ("feng-dao", "the-long-happy-old-man")]),
    ("每天做的事跟我在意的相反。",
     [("maslach", "six-mismatches"), ("frankl", "happiness-ensues")]),
]),
("要不要跳槽", "跟人打交道", [
    ("还待得下去吗，我不确定。",
     [("boyd", "to-be-or-to-do"), ("zhang-yiming", "delayed-gratification")]),
    ("钱和成长，我该先要哪个？",
     [("naval", "productize-yourself"), ("buffett", "circle-of-competence")]),
    ("平台给我流量，可人不是我的。",
     [("kevin-kelly", "direct-relationship"), ("naval", "assets-while-you-sleep")]),
]),
("信错了人", "跟人打交道", [
    ("我信错了人，现在不敢再信谁。",
     [("konnikova", "not-manufacturing-trust"), ("analects", "see-how")]),
    ("回头看破绽很明显，当时我就是没看见。",
     [("konnikova", "not-manufacturing-trust"), ("konnikova", "transition-is-the-window")]),
    ("被坑过一次，我现在谁都防。",
     [("analects", "see-how"), ("han-feizi", "not-counting-on-goodness")]),
    ("我心软，一次次给他机会。",
     [("adler", "separation-of-tasks"), ("han-feizi", "two-handles")]),
]),
("一个能约的人都没有", "跟人打交道", [
    ("来了三年，我一个能约的人都没有。",
     [("cacioppo", "loneliness-is-a-signal"), ("harvard-study", "social-fitness")]),
    ("人不少，可没一个说得上话的。",
     [("cacioppo", "loneliness-is-a-signal"), ("harvard-study", "someone-to-count-on")]),
    ("我总觉得别人在躲我。",
     [("cacioppo", "hypervigilance"), ("brene-brown", "secrecy-silence-judgment")]),
    ("活动我去了不少，回来还是一个人。",
     [("cacioppo", "not-more-socializing"), ("harvard-study", "social-fitness")]),
    ("想约人，可话到嘴边发不出去。",
     [("cacioppo", "not-more-socializing"), ("cacioppo", "hypervigilance")]),
    ("半夜出事，我不知道能打给谁。",
     [("harvard-study", "someone-to-count-on"), ("granovetter", "weak-ties")]),
    ("朋友都成家了，我们聊不到一起。",
     [("harvard-study", "social-fitness"), ("granovetter", "no-strong-tie-is-a-bridge")]),
    ("想认识新的人，我不知道从哪起。",
     [("granovetter", "weak-ties"), ("harvard-study", "social-fitness")]),
    ("一到人多的场合我就发紧。",
     [("cacioppo", "hypervigilance"), ("satir", "coping-stances")]),
]),

# ── 家庭与关系 ──
("跟伴侣吵", "家里的事", [
    ("同一件事我们吵了很多次了。",
     [("gottman", "four-horsemen"), ("nonviolent-communication", "needs-behind-blame")]),
    ("话说重了，还修得回来吗？",
     [("gottman", "repair-attempts"), ("crucial-conversations", "safety-first")]),
    ("我们说的根本不是同一件事。",
     [("satir", "iceberg"), ("thomas-gordon", "i-message")]),
    ("我们一吵就收不住。",
     [("gottman", "four-horsemen"), ("gottman", "repair-attempts")]),
    ("为了孩子，我们一直硬撑着。",
     [("gottman", "four-horsemen"), ("harvard-study", "relationships-predict-health")]),
]),
("孩子不听", "家里的事", [
    ("说了很多遍，他还是不做。",
     [("montessori", "prepared-environment"), ("adler", "separation-of-tasks")]),
    ("我该管到什么程度？",
     [("adler", "separation-of-tasks"), ("montessori", "help-me-do-it-myself")]),
    ("我说的每句他都顶回来。",
     [("thomas-gordon", "i-message"), ("thomas-gordon", "problem-ownership")]),
    ("说了多少遍，他就是不做。",
     [("montessori", "prepared-environment"), ("montessori", "help-me-do-it-myself")]),
    ("孩子沉迷手机，说了也没用。",
     [("xunzi", "borrow-from-things"), ("montessori", "prepared-environment")]),
    ("孩子在学校被人欺负了。",
     [("thomas-gordon", "problem-ownership"), ("montessori", "prepared-environment")]),
]),
("孩子不说话", "家里的事", [
    ("他什么都不跟我讲了。",
     [("attachment-theory", "strange-situation"), ("carl-rogers", "unconditional-regard")]),
    ("我怎么让他愿意开口？",
     [("carl-rogers", "reflective-listening"), ("nonviolent-communication", "observation-not-evaluation")]),
    ("他有事也不跟我讲了。",
     [("thomas-gordon", "problem-ownership"), ("satir", "iceberg")]),
    ("我一开口，他就把门关上了。",
     [("nonviolent-communication", "observation-not-evaluation"), ("carl-rogers", "reflective-listening")]),
]),
("被家人的情绪裹着", "家里的事", [
    ("家里一有事，我整个人就乱了。",
     [("seneca", "on-anger"), ("epictetus", "dichotomy")]),
    ("我是该迁就，还是干脆躲远点？",
     [("adler", "separation-of-tasks"), ("attachment-theory", "secure-base")]),
    ("家里一有事，我就没了自己。",
     [("bowen", "differentiation"), ("satir", "coping-stances")]),
    ("一到家里，我就变成另一个人。",
     [("satir", "coping-stances"), ("attachment-theory", "secure-base")]),
]),
("父母催得紧", "家里的事", [
    ("我每次回家都要吵一轮。",
     [("adler", "separation-of-tasks"), ("nonviolent-communication", "needs-behind-blame")]),
    ("我怎么说才不伤人也不妥协？",
     [("chris-voss", "labeling"), ("crucial-conversations", "start-with-heart")]),
    ("他们的着急全压在我身上。",
     [("bowen", "triangles"), ("bowen", "differentiation")]),
    ("又吵起来了，我已经忘了为什么。",
     [("crucial-conversations", "start-with-heart"), ("chris-voss", "labeling")]),
    ("两个人的事，总要拉进第三个人。",
     [("bowen", "triangles"), ("adler", "teleology")]),
]),
("身边人不敢跟我说真话", "家里的事", [
    ("他们只报好消息给我。",
     [("carl-rogers", "unconditional-regard"), ("attachment-theory", "strange-situation")]),
    ("我上次的反应，是不是把人吓住了？",
     [("crucial-conversations", "safety-first"), ("cao-cao", "burning-the-letters")]),
    ("等我知道的时候，事已经砸了。",
     [("crucial-conversations", "safety-first"), ("strategies-of-the-warring-states", "three-mirrors")]),
    ("我问了，他们还是说没事。",
     [("carl-rogers", "reflective-listening"), ("socrates", "midwifery")]),
]),
("家里的活没人算", "家里的事", [
    ("我做的这些，好像不算数。",
     [("hochschild", "second-shift"), ("hochschild", "emotional-labor")]),
    ("我在家全天连轴转，还被说没上班。",
     [("hochschild", "second-shift"), ("satir", "coping-stances")]),
    ("这些事总落在我头上。",
     [("hochschild", "second-shift"), ("thomas-gordon", "i-message")]),
    ("我一提，就变成我在抱怨。",
     [("nonviolent-communication", "observation-not-evaluation"), ("satir", "iceberg")]),
]),
("照顾老人", "家里的事", [
    ("爸妈老了，我不知道能做什么。",
     [("hochschild", "second-shift"), ("thomas-gordon", "problem-ownership")]),
    ("照顾他，把我自己也耗空了。",
     [("hochschild", "emotional-labor"), ("sapolsky", "stress-mismatch")]),
    ("兄弟姐妹几个，就我在管。",
     [("thomas-gordon", "problem-ownership"), ("hochschild", "second-shift")]),
    ("我又想尽孝，又想过自己的日子。",
     [("adler", "separation-of-tasks"), ("kristin-neff", "three-parts")]),
    ("治不好了，我还能做什么。",
     [("kleinman", "caring-when-curing-fails"), ("frankl", "the-last-freedom")]),
    ("照顾了两年，我自己先垮了。",
     [("kleinman", "caring-when-curing-fails"), ("hochschild", "emotional-labor")]),
]),
("被背叛了", "家里的事", [
    ("他背着我做了那件事。",
     [("gottman", "four-horsemen"), ("konnikova", "not-manufacturing-trust")]),
    ("我原谅了，可心里过不去。",
     [("gottman", "repair-attempts"), ("epictetus", "judgments-not-things")]),
    ("还要不要继续，我拿不定。",
     [("han-xin", "neither-nor"), ("li-ka-shing", "knowing-when-to-stop")]),
]),
("在一起久了没感觉", "家里的事", [
    ("在一起很多年，没感觉了。",
     [("perel", "security-and-desire"), ("perel", "not-a-problem-to-solve")]),
    ("不吵也不亲，我不知道算什么。",
     [("perel", "not-a-problem-to-solve"), ("gottman", "four-horsemen")]),
    ("天天在一起，却越来越远。",
     [("perel", "quality-not-frequency"), ("harvard-study", "someone-to-count-on")]),
    ("异地两年，我们越来越没话说。",
     [("perel", "quality-not-frequency"), ("perel", "security-and-desire")]),
    ("要不要分，我一直定不下来。",
     [("perel", "not-a-problem-to-solve"), ("li-ka-shing", "knowing-when-to-stop")]),
]),

# ── 身心与生活 ──
("睡不好", "身体与精力", [
    ("我一躺下脑子就停不下来。",
     [("john-ratey", "move-before-you-think"), ("seneca", "on-anger")]),
    ("睡够了还是觉得累。",
     [("john-ratey", "exercise-for-the-brain"), ("cal-newport", "attention-residue")]),
    ("越怕睡不着，就越睡不着。",
     [("frankl", "happiness-ensues"), ("sapolsky", "predictability")]),
    ("睡前那会儿，白天的事全回来了。",
     [("marcus-aurelius", "morning-preparation"), ("cal-newport", "attention-residue")]),
    ("长期失眠，什么办法都试过了。",
     [("john-ratey", "move-before-you-think"), ("sapolsky", "predictability")]),
]),
("精力跟不上", "身体与精力", [
    ("一到下午我就废了。",
     [("john-ratey", "exercise-for-the-brain"), ("cal-newport", "schedule-the-depth")]),
    ("我是不是一直在硬撑？",
     [("seneca", "on-shortness-of-life"), ("john-ratey", "move-before-you-think")]),
    ("我最好的状态去哪了？",
     [("csikszentmihalyi", "leisure-paradox"), ("sapolsky", "stress-mismatch")]),
    ("我拿身体换事业，值不值。",
     [("harvard-study", "relationships-predict-health"), ("li-ka-shing", "knowing-when-to-stop")]),
]),
("坐不住", "身体与精力", [
    ("我一会儿就想去看手机。",
     [("cal-newport", "attention-residue"), ("atomic-habits", "identity-first")]),
    ("整块时间总是被切碎。",
     [("cal-newport", "schedule-the-depth"), ("seneca", "on-shortness-of-life")]),
    ("我一坐下就想干点别的。",
     [("csikszentmihalyi", "flow-channel"), ("bj-fogg", "anchor-and-celebrate")]),
    ("太难我慌，太简单我又走神。",
     [("csikszentmihalyi", "flow-channel"), ("csikszentmihalyi", "leisure-paradox")]),
    ("我一坐下就被打断。",
     [("murakami", "focus-and-endurance"), ("cal-newport", "schedule-the-depth")]),
]),
("想改个习惯", "身体与精力", [
    ("我下过很多次决心，每次都断。",
     [("atomic-habits", "identity-first"), ("adler", "teleology")]),
    ("我怎么才能坚持下来？",
     [("atomic-habits", "systems-over-goals"), ("franklin", "one-virtue-a-week")]),
    ("每次都靠咬牙，撑不了几天。",
     [("bj-fogg", "tiny-habits"), ("bj-fogg", "anchor-and-celebrate")]),
    ("我一直在练，可就是没长进。",
     [("ericsson", "not-ten-thousand-hours"), ("vygotsky", "zpd")]),
    ("热情一过，我就断了。",
     [("murakami", "focus-and-endurance"), ("bj-fogg", "tiny-habits")]),
]),
("长期紧绷", "身体与精力", [
    ("我好像很久没真正松下来了。",
     [("seneca", "on-shortness-of-life"), ("john-ratey", "move-before-you-think")]),
    ("这样下去我会不会垮？",
     [("john-ratey", "exercise-for-the-brain"), ("epictetus", "dichotomy")]),
    ("我这根弦绷了太久了。",
     [("sapolsky", "stress-mismatch"), ("sapolsky", "predictability")]),
    ("压力不算大，我却一直绷着。",
     [("sapolsky", "predictability"), ("nietzsche", "gazing-into-abyss")]),
]),
("想戒又戒不掉", "身体与精力", [
    ("戒了很多次，我每次都破功。",
     [("rat-park", "change-the-cage"), ("bj-fogg", "tiny-habits")]),
    ("一到晚上我就控制不住。",
     [("rat-park", "change-the-cage"), ("rat-park", "rat-park")]),
    ("我知道不好，可就是停不下来。",
     [("rat-park", "rat-park"), ("wang-yangming", "unity-of-knowing-and-doing")]),
    ("是不是我意志力太差了。",
     [("rat-park", "vietnam-veterans"), ("montessori", "prepared-environment")]),
    ("换了环境，我还是老样子。",
     [("rat-park", "vietnam-veterans"), ("rat-park", "change-the-cage")]),
]),
("干不动了", "身体与精力", [
    ("我不是累，是整个人空了。",
     [("maslach", "three-signs"), ("frankl", "happiness-ensues")]),
    ("我每天醒来都不想起床。",
     [("maslach", "three-signs"), ("john-ratey", "move-before-you-think")]),
    ("做完什么都没有满足感了。",
     [("maslach", "three-signs"), ("csikszentmihalyi", "flow-channel")]),
    ("身体越来越差，我却停不下来。",
     [("maslach", "fix-the-job"), ("lee-kuan-yew", "from-my-sickbed")]),
    ("休个假回来，还是那张表。",
     [("maslach", "fix-the-job"), ("maslach", "six-mismatches")]),
    ("事不多，可每件都要请示。",
     [("maslach", "six-mismatches"), ("sapolsky", "predictability")]),
]),
("时间不够用", "身体与精力", [
    ("一天下来，没一件是我自己的事。",
     [("seneca", "on-shortness-of-life"), ("cal-newport", "schedule-the-depth")]),
    ("我到底该砍掉哪一块？",
     [("franklin", "one-virtue-a-week"), ("atomic-habits", "systems-over-goals")]),
    ("家里的活，我好像永远做不完。",
     [("hochschild", "second-shift"), ("cal-newport", "schedule-the-depth")]),
]),
("病了", "身体与精力", [
    ("检查结果出来了，我不敢看。",
     [("marcus-aurelius", "view-from-above"), ("su-shi", "no-wind-no-rain")]),
    ("这个病要跟我过一辈子。",
     [("sapolsky", "predictability"), ("epictetus", "judgments-not-things")]),
    ("家里人病了，我撑着不能倒。",
     [("john-ratey", "exercise-for-the-brain"), ("hochschild", "emotional-labor")]),
    ("查出个病，我要吃一辈子药了。",
     [("kleinman", "disease-and-illness"), ("epictetus", "dichotomy")]),
    ("指标都正常，我还是不敢出门。",
     [("kleinman", "disease-and-illness"), ("sapolsky", "predictability")]),
    ("我最怕的那点，医生没问过。",
     [("kleinman", "eight-questions"), ("carl-rogers", "reflective-listening")]),
]),


# ── 人生转折点：低频但高强度，人最会主动搜的时刻 ──
# ── 刚起步：13 篇章节早就在库里（优秀的绵羊、艾利克森、维果茨基、纽波特…），
#    但 76 个处境里没有一个说的是「第一份工作」「要不要读研」。
#    内容存在、走不到，和当初 9 个家庭条目挂不上处境是同一种事故。
#    这一组不写新内容，只接线。 ──
("一路优秀，突然没了标准", "刚起步", [
    ("从小按分数活，现在没人给我打分了。",
     [("excellent-sheep", "hurdles"), ("excellent-sheep", "no-scoreboard")]),
    ("我一直很优秀，可我不知道要去哪。",
     [("jobs", "connecting-the-dots"), ("socrates", "knowing-not-knowing")]),
    ("没人给我题了，我不知道做什么。",
     [("excellent-sheep", "no-scoreboard"), ("socrates", "midwifery")]),
    ("我做的每件事都是为了给人看。",
     [("excellent-sheep", "no-scoreboard"), ("frankl", "happiness-ensues")]),
]),
("第一份工作", "刚起步", [
    ("刚进来，我什么都不会。",
     [("vygotsky", "zpd"), ("ericsson", "deliberate-practice")]),
    ("我不知道该问人还是自己扛。",
     [("vygotsky", "scaffolding"), ("socrates", "midwifery")]),
    ("我干的活好像谁都能干。",
     [("naval", "productize-yourself"), ("naval", "assets-while-you-sleep")]),
    ("我这个位置太边缘，学不到东西。",
     [("einstein", "patent-office"), ("murakami", "no-one-asked-you-to")]),
    ("我不知道自己不知道什么。",
     [("thinking-fast-and-slow", "wysiati"), ("socrates", "knowing-not-knowing")]),
]),
("要不要接着读书", "刚起步", [
    ("读还是工作，我怕选错了。",
     [("thinking-fast-and-slow", "loss-aversion"), ("huang", "strategic-retreat")]),
    ("别人都在卷学历，我慌了。",
     [("ericsson", "not-ten-thousand-hours"), ("dweck", "effect-size")]),
    ("多读几年，我怕跟社会脱节。",
     [("ericsson", "deliberate-practice"), ("bruce-lee", "be-water")]),
    ("这书我是为自己读还是为交代。",
     [("excellent-sheep", "no-scoreboard"), ("wang-yangming", "innate-knowing")]),
]),
("学的用不上", "刚起步", [
    ("学校教我的那套，在这儿对不上。",
     [("feynman", "teach-to-understand"), ("bruce-lee", "be-water")]),
    ("我看着都会，一动手就不行。",
     [("wang-yangming", "unity-of-knowing-and-doing"), ("wang-yangming", "polish-on-things")]),
    ("背了一堆，用的时候想不起来。",
     [("feynman", "teach-to-understand"), ("ericsson", "deliberate-practice")]),
    ("我不知道该从哪儿开始练。",
     [("vygotsky", "zpd"), ("csikszentmihalyi", "flow-channel")]),
    ("我只会学校教的那一套。",
     [("munger", "latticework"), ("feynman", "teach-to-understand")]),
]),

("突然没了工作", "人生转弯", [
    ("干了这么多年，说没就没了。",
     [("huang", "strategic-retreat"), ("su-shi", "three-exiles")]),
    ("我接下来该干什么？",
     [("frankl", "the-last-freedom"), ("fan-li", "leave-at-the-top")]),
    ("行业在变，我看不懂往哪去。",
     [("sovereign-individual", "logic-of-violence"), ("guns-germs-steel", "axis-of-continents")]),
    ("四十多了，我不知道还能干什么。",
     [("boyd", "to-be-or-to-do"), ("fan-li", "stock-the-opposite")]),
    ("没了这个身份，我是谁。",
     [("frankl", "the-last-freedom"), ("zhuangzi", "use-of-uselessness")]),
    ("存款撑不了几个月了。",
     [("su-shi", "east-slope"), ("paul-graham", "default-alive")]),
    ("被裁了，我不知道先干什么。",
     [("su-shi", "east-slope"), ("su-shi", "three-exiles")]),
    ("没了那个位置，我先做哪件事。",
     [("su-shi", "east-slope"), ("su-shi", "three-exiles")]),
]),
("重要的人走了", "人生转弯", [
    ("我不知道日子怎么继续。",
     [("frankl", "the-last-freedom"), ("marcus-aurelius", "view-from-above")]),
    ("我总觉得当初还能做点什么。",
     [("epictetus", "dichotomy"), ("zhuangzi", "equalizing-things")]),
    ("半年过去了，我还是缓不过来。",
     [("konnikova", "transition-is-the-window"), ("su-shi", "no-wind-no-rain")]),
    ("别人都往前走了，只有我停着。",
     [("marcus-aurelius", "view-from-above"), ("kristin-neff", "three-parts")]),
    ("我怕时间久了就把他忘了。",
     [("frankl", "the-last-freedom"), ("seneca", "on-shortness-of-life")]),
    ("养了十几年的狗没了。",
     [("konnikova", "transition-is-the-window"), ("kleinman", "caring-when-curing-fails")]),
]),
("要重新开始", "人生转弯", [
    ("我这个年纪从头来，太晚了吗？",
     [("su-shi", "three-exiles"), ("nietzsche", "what-does-not-kill")]),
    ("过去那些年是不是白费了？",
     [("dalio", "pain-plus-reflection"), ("frankl", "happiness-ensues")]),
    ("退路已经没有了，只能往前。",
     [("xiang-yu", "sinking-the-boats"), ("han-xin", "back-to-the-river")]),
    ("从头再来的地方，我该先干什么。",
     [("su-shi", "three-exiles"), ("su-shi", "no-wind-no-rain")]),
]),
("扛不动了", "人生转弯", [
    ("我快撑不住了，但不能倒。",
     [("marcus-aurelius", "obstacle-is-the-way"), ("epictetus", "dichotomy")]),
    ("我撑下去，图的是什么？",
     [("frankl", "the-last-freedom"), ("nietzsche", "what-does-not-kill")]),
    ("我兵力不如人，只能这么耗着。",
     [("napoleon", "decisive-point"), ("mao", "on-protracted-war")]),
    ("这事赢不了，我只能一直带着。",
     [("kleinman", "caring-when-curing-fails"), ("frankl", "the-last-freedom")]),
]),
("换个地方重来", "人生转弯", [
    ("换了城市，我谁也不认识。",
     [("granovetter", "weak-ties"), ("konnikova", "transition-is-the-window")]),
    ("到了新地方，机会一个都不找上门。",
     [("granovetter", "weak-ties"), ("granovetter", "no-strong-tie-is-a-bridge")]),
    ("圈子就这么大，我听不到新消息。",
     [("granovetter", "no-strong-tie-is-a-bridge"), ("sovereign-individual", "logic-of-violence")]),
    ("换了城市，熟人一个都没了。",
     [("harvard-study", "social-fitness"), ("granovetter", "weak-ties")]),
    ("我想换个国家生活。",
     [("granovetter", "weak-ties"), ("harvard-study", "social-fitness")]),
]),
("人到中年", "人生转弯", [
    ("四十了，我忽然觉得来不及。",
     [("jung", "afternoon-of-life"), ("seneca", "on-shortness-of-life")]),
    ("该有的都有了，我却更空。",
     [("jung", "afternoon-of-life"), ("frankl", "happiness-ensues")]),
    ("我这些年一直在演一个角色。",
     [("jung", "the-persona"), ("hochschild", "emotional-labor")]),
    ("身份没了，我不知道自己是谁。",
     [("jung", "the-persona"), ("frankl", "the-last-freedom")]),
    ("越使劲越空，我不懂为什么。",
     [("jung", "afternoon-of-life"), ("zhuangzi", "use-of-uselessness")]),
]),

# ── 无能为力：现有全站语气都是「怎么解决」，接不住这类人 ──
("事情我说了不算", "使不上劲", [
    ("这件事根本不由我决定。",
     [("epictetus", "dichotomy"), ("machiavelli", "fortune-and-virtu")]),
    ("我还能做点什么？",
     [("marcus-aurelius", "obstacle-is-the-way"), ("mandela", "rivonia")]),
    ("规则别人定的，我怎么办？",
     [("sovereign-individual", "citizen-to-customer"), ("guns-germs-steel", "yalis-question")]),
    ("这些规矩谁定的，我就得认吗？",
     [("sapiens", "fictions-that-cooperate"), ("finite-and-infinite-games", "playing-with-boundaries")]),
    ("轮不到我定，我还能管什么。",
     [("epictetus", "dichotomy"), ("epictetus", "judgments-not-things")]),
]),
("已经改不了了", "使不上劲", [
    ("这事已经发生了，我改不了。",
     [("epictetus", "judgments-not-things"), ("su-shi", "no-wind-no-rain")]),
    ("我怎么才能不再反复想它？",
     [("huineng", "originally-not-a-thing"), ("zhuangzi", "equalizing-things")]),
    ("我们的差距是怎么拉开的？",
     [("guns-germs-steel", "yalis-question"), ("on-war", "continuation-of-politics")]),
    ("换了新领导，还是老样子。",
     [("old-regime", "centralization-survived"), ("why-nations-fail", "two-nogales")]),
    ("木已成舟，我还在跟它较劲。",
     [("zhuangzi", "equalizing-things"), ("zhuangzi", "ox-carving")]),
]),
("努力也没用", "使不上劲", [
    ("该做的我都做了，还是没用。",
     [("xunzi", "constant-heaven"), ("machiavelli", "fortune-and-virtu")]),
    ("那还要不要接着做？",
     [("tao-te-ching", "wu-wei"), ("frankl", "happiness-ensues")]),
    ("起点就不一样，我使劲有用吗？",
     [("xunzi", "constant-heaven"), ("mandela", "rivonia")]),
]),
("一直没成", "使不上劲", [
    ("这事我做了很多年，一直没成。",
     [("pu-songling", "forty-years-of-failing"), ("murakami", "no-one-asked-you-to")]),
    ("考了很多年，我一直没考上。",
     [("pu-songling", "forty-years-of-failing"), ("pu-songling", "collecting-at-the-roadside")]),
    ("每次都差一点，我不知道该不该停。",
     [("pu-songling", "forty-years-of-failing"), ("li-ka-shing", "knowing-when-to-stop")]),
    ("一年下来，只剩「又没成」这一句。",
     [("pu-songling", "forty-years-of-failing"), ("maslach", "three-signs")]),
]),
("主线没成副业成了", "回头与往前", [
    ("正职平平，业余那件却越做越好。",
     [("pu-songling", "the-side-thing"), ("naval", "productize-yourself")]),
    ("我该不该把副业换成主业。",
     [("pu-songling", "the-side-thing"), ("li-ka-shing", "knowing-when-to-stop")]),
    ("花力气的没结果，随手的反而成了。",
     [("pu-songling", "the-side-thing"), ("jobs", "connecting-the-dots")]),
    ("只有碎时间，我也不敢辞职。",
     [("pu-songling", "collecting-at-the-roadside"), ("murakami", "focus-and-endurance")]),
]),
("被晾在一边", "使不上劲", [
    ("我被调岗了，明摆着是边缘化。",
     [("su-shi", "three-exiles"), ("grove", "inflection-and-cassandras")]),
    ("我手上的活越来越没分量。",
     [("su-shi", "three-exiles"), ("zhuge-liang", "longzhong-plan")]),
    ("会不叫我了，事也不找我了。",
     [("grove", "inflection-and-cassandras"), ("han-xin", "neither-nor")]),
    ("我该等风头过去，还是走。",
     [("li-ka-shing", "knowing-when-to-stop"), ("fan-li", "leave-at-the-top")]),
]),

# ── 说不出口的：搜索量大、私密、典籍最擅长 ──
("看不得别人好", "说不出口", [
    ("我朋友过得好，我心里不是滋味。",
     [("liu-bang", "three-i-cannot"), ("zhuangzi", "equalizing-things")]),
    ("我怎么老在跟人比？",
     [("epictetus", "dichotomy"), ("su-shi", "no-bad-people")]),
    ("看到同事升了，我笑不出来。",
     [("liu-bang", "three-i-cannot"), ("kristin-neff", "not-self-esteem")]),
    ("我这样想，是不是很小人。",
     [("brene-brown", "guilt-not-shame"), ("kristin-neff", "three-parts")]),
    ("我一见那种人就来气。",
     [("jung", "the-shadow"), ("brene-brown", "guilt-not-shame")]),
]),
("我做错了事", "说不出口", [
    ("那件事是我不对，我过不去。",
     [("wang-yangming", "bandits-in-the-heart"), ("zeng-guofan", "self-watch")]),
    ("道歉之后呢，就这样了吗？",
     [("gandhi", "means-are-seeds"), ("dalio", "pain-plus-reflection")]),
    ("我想把它记下来，又怕难看。",
     [("records-of-the-grand-historian", "no-praise-no-hiding"), ("zizhi-tongjian", "what-to-keep")]),
    ("过去很久了，我还是觉得自己很糟。",
     [("brene-brown", "guilt-not-shame"), ("zeng-guofan", "self-watch")]),
    ("我一直在解释，越解释越糟。",
     [("su-shi", "no-more-writing"), ("brene-brown", "guilt-not-shame")]),
    ("我做了对不起人的事，一直没说。",
     [("brene-brown", "secrecy-silence-judgment"), ("brene-brown", "guilt-not-shame")]),
]),
("怕被看穿", "说不出口", [
    ("我怕别人发现我其实不行。",
     [("socrates", "knowing-not-knowing"), ("zeng-guofan", "self-watch")]),
    ("坐在这个位置上，我心里发虚。",
     [("liu-bang", "three-i-cannot"), ("wang-yangming", "polish-on-things")]),
    ("我在做的事，经得起看吗？",
     [("hu-xueyan", "no-cheating"), ("mencius", "flood-like-qi")]),
    ("有件事我谁都没说过。",
     [("brene-brown", "secrecy-silence-judgment"), ("carl-rogers", "unconditional-regard")]),
    ("我怕的那一仗，其实在自己心里。",
     [("wang-yangming", "bandits-in-the-heart"), ("wang-yangming", "innate-knowing")]),
    ("我想争一个「你承认我没错」。",
     [("su-shi", "no-more-writing"), ("epictetus", "judgments-not-things")]),
]),
("放不下一个人", "说不出口", [
    ("我到现在还恨那个人。",
     [("wang-yangming", "bandits-in-the-heart"), ("mandela", "springbok-jersey")]),
    ("原谅是不是等于我认了？",
     [("mandela", "springbok-jersey"), ("su-shi", "no-bad-people")]),
    ("都过去这么久了，我还在想他。",
     [("su-shi", "no-wind-no-rain"), ("huineng", "originally-not-a-thing")]),
    ("我删了又加回来，反反复复。",
     [("adler", "teleology"), ("wang-yangming", "bandits-in-the-heart")]),
]),
("开始怕死", "说不出口", [
    ("夜里想到死，就睡不着了。",
     [("epictetus", "dichotomy"), ("seneca", "on-shortness-of-life")]),
    ("我怕的是死，还是没活过。",
     [("frankl", "happiness-ensues"), ("marcus-aurelius", "view-from-above")]),
    ("时间在少，我却什么都没做成。",
     [("seneca", "on-shortness-of-life"), ("su-shi", "no-wind-no-rain")]),
    ("这件事我跟谁都开不了口。",
     [("brene-brown", "secrecy-silence-judgment"), ("kristin-neff", "three-parts")]),
]),

# ── 时间尺度：回头看与往前看 ──
("那件事一直搁在心里", "回头与往前", [
    ("过了这么久我还是耿耿于怀。",
     [("su-shi", "no-wind-no-rain"), ("huineng", "originally-not-a-thing")]),
    ("当年那个决定，是不是错了？",
     [("dalio", "pain-plus-reflection"), ("munger", "invert")]),
    ("我没说出口的那句，堵到现在。",
     [("brene-brown", "secrecy-silence-judgment"), ("thomas-gordon", "i-message")]),
    ("现在想起来还是脸发烫。",
     [("brene-brown", "guilt-not-shame"), ("kristin-neff", "three-parts")]),
]),
("不知道要什么", "回头与往前", [
    ("我说不出自己到底想要什么。",
     [("frankl", "happiness-ensues"), ("zhuangzi", "use-of-uselessness")]),
    ("五年后我想成为什么样的人？",
     [("wang-yangming", "innate-knowing"), ("tao-te-ching", "usefulness-of-emptiness")]),
    ("我只会问怎样算做得好。",
     [("excellent-sheep", "no-scoreboard"), ("excellent-sheep", "hurdles")]),
    ("日子越过越好，我却越来越不快活。",
     [("sapiens", "wheat-domesticated-us"), ("finite-and-infinite-games", "two-kinds")]),
]),
("路太多，选不出来", "回头与往前", [
    ("每条路看着都成立，我选不出来。",
     [("boyd", "to-be-or-to-do"), ("excellent-sheep", "hurdles")]),
    ("我在往上走，可这不是我要的。",
     [("boyd", "to-be-or-to-do"), ("zhuangzi", "use-of-uselessness")]),
    ("可能性太多了，我反而不敢动。",
     [("jobs", "focus-is-saying-no"), ("bismarck", "art-of-the-possible")]),
    ("我想做的和该做的，是两件事。",
     [("excellent-sheep", "no-scoreboard"), ("frankl", "happiness-ensues")]),
    ("做了这么多，我反而更迷茫了。",
     [("excellent-sheep", "hurdles"), ("huineng", "originally-not-a-thing")]),
]),
("要不要现在转向", "回头与往前", [
    ("我现在换轨道，太冒险吗？",
     [("fan-li", "leave-at-the-top"), ("tao-te-ching", "reversal")]),
    ("我怎么知道该坚持还是该改？",
     [("munger", "invert"), ("huang", "strategic-retreat")]),
    ("该转了，可现在做得好好的。",
     [("innovators-dilemma", "good-management-fails"), ("grove", "revolving-door")]),
    ("现在做得好好的，我该转吗。",
     [("grove", "inflection-and-cassandras"), ("grove", "revolving-door")]),
]),

]
