# -*- coding: utf-8 -*-
"""English situation layer — the entry point for /en/.

Same shape as hwx_scenes.SCENES: (situation, group, [(question, [(slug, k)…])…]).

These are **not** translations of the Chinese questions. The Chinese reader
arrives by name — 苏轼, 王阳明 — because the names carry weight. The English
reader has never heard of them. Almost every entry in this first batch is a
stranger, so the only way in is the situation: somebody types "I got passed
over" or "why am I still not over this", and the situation catches them.

So each line is written the way an English speaker actually says it to
themselves at 2am, in the first person, concrete, no abstraction. Where the
Chinese had two near-identical phrasings pointing at the same chapter, the
English keeps both but makes them genuinely different ways in — that is the
point of having more than one.
"""

SCENES = [

# ── Making a call ──
("Anger just took over", "Making a call", [
    ("It hit me and I can't cool down.",
     [("su-shi", "no-wind-no-rain")]),
    ("Some people set me off and I can't say why.",
     [("jung", "the-shadow")]),
]),
("It turned into a fight", "Making a call", [
    ("Neither of us will be the one to back down.",
     [("gottman", "repair-attempts")]),
    ("He meant it. Do I still let it go?",
     [("su-shi", "no-bad-people")]),
]),
("I keep not starting", "Making a call", [
    ("I understand it completely and still don't move.",
     [("wang-yangming", "unity-of-knowing-and-doing")]),
    ("I keep preparing instead of starting.",
     [("boyd", "ooda")]),
    ("I know what to do. I'm not doing it.",
     [("wang-yangming", "unity-of-knowing-and-doing")]),
]),
("A decision I can't undo", "Making a call", [
    ("If this is wrong, is there a way back?",
     [("li-ka-shing", "ninety-percent-failure")]),
]),
("I don't have enough information", "Making a call", [
    ("By the time the data is in, will it be too late?",
     [("boyd", "ooda")]),
]),
("They said no to my plan", "Making a call", [
    ("Do I push, or do I take the no?",
     [("boyd", "to-be-or-to-do")]),
]),

# ── Facing an opponent ──
("They're setting the pace", "Facing an opponent", [
    ("I'm only ever reacting. I never set the tempo.",
     [("boyd", "ooda")]),
]),
("After the win", "Facing an opponent", [
    ("I won, and now I don't know when to stop.",
     [("li-ka-shing", "knowing-when-to-stop")]),
]),

# ── Money ──
("Making money work", "Money", [
    ("Cash sitting still makes me anxious.",
     [("fan-li", "stock-the-opposite")]),
]),
("Not enough money", "Money", [
    ("This month is on me. I can't think about next year.",
     [("li-ka-shing", "knowing-when-to-stop")]),
    ("I can't pay it back and I haven't told anyone at home.",
     [("li-ka-shing", "ninety-percent-failure")]),
    ("Money fights are pushing us apart.",
     [("hochschild", "second-shift")]),
    ("The income stopped. What do I do first?",
     [("su-shi", "east-slope")]),
]),

# ── Dealing with people ──
("Can I trust this person", "Dealing with people", [
    ("He says all the right things and I'm not sure I believe him.",
     [("han-feizi", "form-and-name")]),
    ("He talks well. I've never seen him deliver.",
     [("han-feizi", "form-and-name")]),
]),
("I don't believe what my boss says", "Dealing with people", [
    ("I've stopped believing the promises.",
     [("han-feizi", "form-and-name")]),
    ("What I was promised falls through, over and over.",
     [("han-feizi", "form-and-name")]),
]),
("They've started watching me", "Dealing with people", [
    ("I did too well and now it makes me nervous.",
     [("fan-li", "leave-at-the-top")]),
]),
("Do I trust my gut", "Dealing with people", [
    ("Can I trust what my gut is telling me this time?",
     [("wang-yangming", "innate-knowing")]),
]),
("Someone is being unreasonable", "Dealing with people", [
    ("Do I fight the way he fights?",
     [("su-shi", "no-bad-people")]),
]),
("I can't stop pleasing people", "Dealing with people", [
    ("I say yes, then spend the week regretting it.",
     [("thomas-gordon", "problem-ownership")]),
]),
("My partner and I are falling out", "Dealing with people", [
    ("Splitting the money is going to blow up on us.",
     [("han-feizi", "two-handles")]),
    ("We never wrote it down and now we remember it differently.",
     [("han-feizi", "form-and-name")]),
    ("I want out, and the work still has to get done.",
     [("li-ka-shing", "knowing-when-to-stop")]),
]),
("None of it means anything", "Dealing with people", [
    ("Every day is the same and I don't know what it's for.",
     [("zhuangzi", "use-of-uselessness")]),
    ("I'm good at all of it and I don't know what I want.",
     [("excellent-sheep", "hurdles"), ("excellent-sheep", "no-scoreboard")]),
    ("Do I have to leave this life to find the real one?",
     [("huineng", "in-the-world")]),
    ("What I do all day is the opposite of what I care about.",
     [("maslach", "six-mismatches")]),
]),
("Should I leave this job", "Dealing with people", [
    ("I don't know if I can stay here much longer.",
     [("boyd", "to-be-or-to-do")]),
]),
("I trusted the wrong person", "Dealing with people", [
    ("It happened once and now I don't trust anyone.",
     [("han-feizi", "not-counting-on-goodness")]),
    ("I keep giving him one more chance.",
     [("han-feizi", "two-handles")]),
]),
("I have no one to call", "Dealing with people", [
    ("Three years here and I have no one to call.",
     [("cacioppo", "loneliness-is-a-signal"), ("harvard-study", "social-fitness")]),
    ("I'm around people all day and talk to none of them.",
     [("cacioppo", "loneliness-is-a-signal"), ("harvard-study", "someone-to-count-on")]),
    ("I keep feeling like people are avoiding me.",
     [("cacioppo", "hypervigilance")]),
    ("I go to the things. I come home just as alone.",
     [("cacioppo", "not-more-socializing"), ("harvard-study", "social-fitness")]),
    ("I want to reach out and the message never sends.",
     [("cacioppo", "not-more-socializing"), ("cacioppo", "hypervigilance")]),
    ("If something happened at 2am I don't know who I'd call.",
     [("harvard-study", "someone-to-count-on"), ("granovetter", "weak-ties")]),
    ("My friends all have families now and we've run out of things to say.",
     [("harvard-study", "social-fitness"), ("granovetter", "no-strong-tie-is-a-bridge")]),
    ("I want to meet people and I don't know where to start.",
     [("granovetter", "weak-ties"), ("harvard-study", "social-fitness")]),
    ("A room full of people makes me tighten up.",
     [("cacioppo", "hypervigilance")]),
]),

# ── Leading people ──
("The same mistakes keep happening", "Leading people", [
    ("We fell into the same hole again.",
     [("han-feizi", "not-counting-on-goodness")]),
    ("New people, same mistakes.",
     [("han-feizi", "not-counting-on-goodness")]),
]),
("The team has gone flat", "Leading people", [
    ("I've tried rewards and I've tried consequences. Neither moved anything.",
     [("han-feizi", "two-handles")]),
    ("How do I push them without breaking them?",
     [("vygotsky", "scaffolding"), ("dweck", "praise-the-process")]),
]),
("Nothing ships", "Leading people", [
    ("I explained it and what came back was not it.",
     [("wiener", "feedback-not-command")]),
    ("What I ask for and what I get are never the same thing.",
     [("han-feizi", "form-and-name")]),
]),

# ── Getting it done ──
("Starting from nothing", "Getting it done", [
    ("I can't even work out how long I can last.",
     [("li-ka-shing", "ninety-percent-failure")]),
]),
("Things are going well and it scares me", "Getting it done", [
    ("Everything's fine. What should I be getting ready for?",
     [("fan-li", "stock-the-opposite")]),
]),
("Nobody is looking at my work", "Getting it done", [
    ("I said it and not one person took it seriously.",
     [("churchill", "no-one-listened")]),
    ("Maybe I just don't have it.",
     [("dweck", "praise-the-process")]),
]),

# ── How you're doing ──
("I'm at the bottom", "How you're doing", [
    ("Nothing to do all day, so I argue with people in my head.",
     [("churchill", "wilderness-years")]),
    ("I don't want to do anything right now.",
     [("cs-lewis", "grief-feels-like-fear"), ("maslach", "three-signs")]),
    ("I lost. Is there anything here worth keeping?",
     [("su-shi", "three-exiles")]),
    ("I don't want to see anyone, and being alone hurts too.",
     [("cacioppo", "loneliness-is-a-signal")]),
]),
("I overthink everything", "How you're doing", [
    ("I ran every outcome and then couldn't move.",
     [("wang-yangming", "bandits-in-the-heart")]),
    ("I keep circling things I can't change.",
     [("wang-yangming", "polish-on-things"), ("huineng", "originally-not-a-thing")]),
    ("I've been in the mud so long I've started to look like it.",
     [("zhuangzi", "ox-carving")]),
    ("There's a voice in my head and it only says cruel things.",
     [("wang-yangming", "bandits-in-the-heart")]),
]),
("I know better and still don't do it", "How you're doing", [
    ("It isn't that I lack resolve. I have two, and they fight.",
     [("wang-yangming", "unity-of-knowing-and-doing")]),
    ("I understand every word of it and I still don't move.",
     [("wang-yangming", "unity-of-knowing-and-doing"), ("wang-yangming", "bandits-in-the-heart")]),
    ("I've practiced for months and can't tell which part I'm doing wrong.",
     [("wiener", "feedback-not-command")]),
    ("Knowing it hasn't once been enough.",
     [("dweck", "praise-the-process")]),
    ("I know exactly what to do. I can't make myself do it.",
     [("dweck", "effect-size")]),
]),
("Nothing I study stays", "How you're doing", [
    ("I read a lot and can't recall any of it when it matters.",
     [("wang-yangming", "polish-on-things")]),
    ("I've done the reps and it still isn't automatic.",
     [("vygotsky", "zpd"), ("vygotsky", "scaffolding")]),
    ("What I learned only works in the shape I learned it.",
     [("huineng", "in-the-world")]),
]),
("Too busy to have a life", "How you're doing", [
    ("My calendar is full and none of it is mine.",
     [("zhuangzi", "use-of-uselessness")]),
    ("The same task costs me more than it costs everyone else.",
     [("zhuangzi", "ox-carving")]),
    ("I finished nothing today and I'm too tired to speak.",
     [("hochschild", "emotional-labor")]),
    ("I gave these years to the work and the friendships went quiet.",
     [("harvard-study", "relationships-predict-health"), ("harvard-study", "social-fitness")]),
]),
("Someone is ahead of me", "How you're doing", [
    ("When people near me do well, something in me goes cold.",
     [("jung", "the-shadow")]),
    ("Is he better than me, or just three years earlier?",
     [("dweck", "praise-the-process")]),
    ("He's a step ahead of me on everything.",
     [("zhuangzi", "equalizing-things")]),
    ("Am I doing the work, or proving something?",
     [("boyd", "to-be-or-to-do")]),
    ("Maybe I was just born with less.",
     [("dweck", "praise-the-process"), ("dweck", "effect-size")]),
]),
("I don't want to race but I'm scared to stop", "How you're doing", [
    ("I don't want to compete and I'm afraid of being left behind.",
     [("zhuangzi", "use-of-uselessness")]),
    ("Everyone stays late. I feel guilty leaving on time.",
     [("zhuangzi", "equalizing-things")]),
]),

# ── When to step back ──
("Should I step back", "When to step back", [
    ("I was only ever taught to advance. Nobody taught me to withdraw.",
     [("fan-li", "leave-at-the-top")]),
    ("When do I leave so that it isn't ugly?",
     [("fan-li", "leave-at-the-top"), ("li-ka-shing", "knowing-when-to-stop")]),
]),

# ── AI arrived ──
("Will my line of work still exist", "AI arrived", [
    ("Right now I'm fine. It's later I'm afraid of.",
     [("fan-li", "stock-the-opposite")]),
    ("The industry is fine. My role is gone.",
     [("fan-li", "stock-the-opposite")]),
    ("I keep finding proof that it isn't actually good.",
     [("kasparov", "excuses-cost-years")]),
    ("It hasn't reached me yet. What do I do first?",
     [("wiener", "wrote-to-the-union")]),
    ("When it does happen, will it be too late to move?",
     [("wiener", "wrote-to-the-union")]),
]),
("I can't keep up with the new thing", "AI arrived", [
    ("The direction changed and I'm still investing in the old one.",
     [("kasparov", "advanced-chess")]),
]),
("My craft stopped being worth anything", "AI arrived", [
    ("What I'm good at, nobody needs right now.",
     [("curie", "the-little-curies"), ("zhuangzi", "use-of-uselessness")]),
    ("It does in seconds what used to be my whole day.",
     [("kasparov", "advanced-chess")]),
    ("The one thing I was best at, it now does better.",
     [("kasparov", "advanced-chess")]),
]),
("The tool does my thinking", "AI arrived", [
    ("I shipped what it gave me without working through it myself.",
     [("kasparov", "process-beats-both")]),
    ("I ask it everything. I've stopped thinking.",
     [("vygotsky", "scaffolding")]),
    ("I handed it in and I can't explain it.",
     [("vygotsky", "scaffolding")]),
    ("Without the tool I can't get the first sentence down.",
     [("vygotsky", "scaffolding")]),
    ("I passed on the answer without checking it.",
     [("kasparov", "process-beats-both")]),
    ("I gave away everything I could and what's left is scraps.",
     [("wiener", "human-use")]),
]),
("More output, emptier", "AI arrived", [
    ("I produce more than I ever did and feel less.",
     [("zhuangzi", "use-of-uselessness")]),
]),
("Do I jump in now", "AI arrived", [
    ("Do I go all in now or wait it out?",
     [("fan-li", "stock-the-opposite")]),
]),
("I don't know what to practice anymore", "AI arrived", [
    ("The bar moves every week. I don't know what to train.",
     [("excellent-sheep", "hurdles")]),
    ("What used to work doesn't count for anything now.",
     [("excellent-sheep", "hurdles")]),
    ("The more useful the task, the sooner it got taken.",
     [("zhuangzi", "use-of-uselessness"), ("excellent-sheep", "hurdles")]),
    ("I can't beat it. So what am I practicing for?",
     [("kasparov", "advanced-chess"), ("excellent-sheep", "hurdles")]),
    ("I work off a ticket queue and never ask why.",
     [("wiener", "human-use"), ("excellent-sheep", "no-scoreboard")]),
]),

# ── At home ──
("We keep fighting", "At home", [
    ("We've had this same fight a hundred times.",
     [("gottman", "four-horsemen")]),
    ("I said something I can't take back. Can this be fixed?",
     [("gottman", "repair-attempts")]),
    ("We are not having the same conversation.",
     [("thomas-gordon", "i-message")]),
    ("Once it starts, neither of us can stop it.",
     [("gottman", "four-horsemen"), ("gottman", "repair-attempts")]),
    ("We're staying together for the kids.",
     [("gottman", "four-horsemen"), ("harvard-study", "relationships-predict-health")]),
]),
("My kid won't listen", "At home", [
    ("I've said it a hundred times and it still doesn't happen.",
     [("montessori", "prepared-environment")]),
    ("How much am I supposed to step in?",
     [("montessori", "help-me-do-it-myself")]),
    ("Every single thing I say comes back at me.",
     [("thomas-gordon", "i-message"), ("thomas-gordon", "problem-ownership")]),
    ("Saying it again has never once worked.",
     [("montessori", "prepared-environment"), ("montessori", "help-me-do-it-myself")]),
    ("The phone has him and nothing I say touches it.",
     [("montessori", "prepared-environment")]),
    ("My kid is being bullied at school.",
     [("thomas-gordon", "problem-ownership"), ("montessori", "prepared-environment")]),
]),
("My kid stopped talking to me", "At home", [
    ("Something's wrong and he isn't telling me.",
     [("thomas-gordon", "problem-ownership")]),
]),
("The work at home doesn't count", "At home", [
    ("Everything I do at home counts as nothing.",
     [("hochschild", "second-shift"), ("hochschild", "emotional-labor")]),
    ("I'm on my feet all day and I'm told I don't work.",
     [("hochschild", "second-shift")]),
    ("It always ends up being me.",
     [("hochschild", "second-shift"), ("thomas-gordon", "i-message")]),
]),
("Caring for a parent", "At home", [
    ("My parents got old and I don't know what I can do.",
     [("hochschild", "second-shift"), ("thomas-gordon", "problem-ownership")]),
    ("Taking care of him has emptied me out.",
     [("hochschild", "emotional-labor"), ("sapolsky", "stress-mismatch")]),
    ("There are four of us and I'm the only one doing it.",
     [("thomas-gordon", "problem-ownership"), ("hochschild", "second-shift")]),
    ("Two years of caring for her and I broke first.",
     [("hochschild", "emotional-labor")]),
]),
("I was betrayed", "At home", [
    ("He did it behind my back.",
     [("gottman", "four-horsemen")]),
    ("I forgave it and I still can't get past it.",
     [("gottman", "repair-attempts")]),
    ("I can't decide whether to stay.",
     [("li-ka-shing", "knowing-when-to-stop")]),
]),
("Years in, nothing left between us", "At home", [
    ("We've been together years and I feel nothing.",
     [("perel", "security-and-desire"), ("perel", "not-a-problem-to-solve")]),
    ("We don't fight and we aren't close. I don't know what this is.",
     [("perel", "not-a-problem-to-solve"), ("gottman", "four-horsemen")]),
    ("We're together every day and further apart every month.",
     [("perel", "quality-not-frequency"), ("harvard-study", "someone-to-count-on")]),
    ("Two years apart and we've run out of things to say.",
     [("perel", "quality-not-frequency"), ("perel", "security-and-desire")]),
    ("I keep almost leaving and never do.",
     [("perel", "not-a-problem-to-solve"), ("li-ka-shing", "knowing-when-to-stop")]),
]),

# ── Body and energy ──
("I can't sleep", "Body and energy", [
    ("The second I lie down my head starts up.",
     [("john-ratey", "move-before-you-think")]),
    ("I slept eight hours and I'm still exhausted.",
     [("john-ratey", "exercise-for-the-brain")]),
    ("The more I worry about sleeping the less I sleep.",
     [("sapolsky", "predictability")]),
    ("I've had insomnia for years and tried everything.",
     [("john-ratey", "move-before-you-think"), ("sapolsky", "predictability")]),
]),
("I've run out of energy", "Body and energy", [
    ("By the afternoon I'm finished.",
     [("john-ratey", "exercise-for-the-brain")]),
    ("Have I just been white-knuckling it this whole time?",
     [("john-ratey", "move-before-you-think")]),
    ("Where did my best hours go?",
     [("sapolsky", "stress-mismatch")]),
    ("I'm trading my body for my career. Is it worth it?",
     [("harvard-study", "relationships-predict-health"), ("li-ka-shing", "knowing-when-to-stop")]),
]),
("I want to change a habit", "Body and energy", [
    ("I practice constantly and I'm not getting better.",
     [("vygotsky", "zpd")]),
]),
("I've been tense for a long time", "Body and energy", [
    ("I can't remember the last time I actually let go.",
     [("john-ratey", "move-before-you-think")]),
    ("Am I heading for a collapse?",
     [("john-ratey", "exercise-for-the-brain")]),
    ("I've been holding this long past what I can hold.",
     [("sapolsky", "stress-mismatch"), ("sapolsky", "predictability")]),
    ("The pressure isn't even that bad and I'm never off.",
     [("sapolsky", "predictability")]),
]),
("I keep trying to quit", "Body and energy", [
    ('"After this stretch is over" — I have said that so many times.',
     [("rat-park", "rat-park")]),
    ("I've quit a dozen times and broken every one.",
     [("rat-park", "change-the-cage")]),
    ("It's fine until night, and then it isn't.",
     [("rat-park", "change-the-cage"), ("rat-park", "rat-park")]),
    ("I know it's bad for me and I can't stop.",
     [("rat-park", "rat-park"), ("wang-yangming", "unity-of-knowing-and-doing")]),
    ("Is my willpower just weak?",
     [("rat-park", "vietnam-veterans"), ("montessori", "prepared-environment")]),
    ("I changed everything around me and I'm exactly the same.",
     [("rat-park", "vietnam-veterans"), ("rat-park", "change-the-cage")]),
]),
("I have nothing left to give", "Body and energy", [
    ("I get two or three usable hours a day.",
     [("maslach", "fix-the-job")]),
    ("It isn't tiredness. There's nothing in there.",
     [("maslach", "three-signs")]),
    ("I wake up already not wanting to.",
     [("maslach", "three-signs"), ("john-ratey", "move-before-you-think")]),
    ("Finishing things stopped feeling like anything.",
     [("maslach", "three-signs")]),
    ("My health is going and I can't make myself stop.",
     [("maslach", "fix-the-job")]),
    ("I took the vacation. The same job was waiting.",
     [("maslach", "fix-the-job"), ("maslach", "six-mismatches")]),
    ("The work is light and I need permission for all of it.",
     [("maslach", "six-mismatches"), ("sapolsky", "predictability")]),
]),
("There's never enough time", "Body and energy", [
    ("The work at home genuinely never ends.",
     [("hochschild", "second-shift")]),
]),
("I got sick", "Body and energy", [
    ("The results came back and I can't open them.",
     [("su-shi", "no-wind-no-rain")]),
    ("This is mine for the rest of my life.",
     [("sapolsky", "predictability")]),
    ("Someone at home is ill and I'm not allowed to fall over.",
     [("john-ratey", "exercise-for-the-brain"), ("hochschild", "emotional-labor")]),
    ("Every test is normal and I still can't leave the house.",
     [("sapolsky", "predictability")]),
]),

# ── Starting out ──
("Straight A's, then no more grades", "Starting out", [
    ("I lived on scores my whole life and now nobody scores me.",
     [("excellent-sheep", "hurdles"), ("excellent-sheep", "no-scoreboard")]),
    ("Nobody hands me the assignment anymore and I'm lost.",
     [("excellent-sheep", "no-scoreboard")]),
    ("Everything I do is for someone to see.",
     [("excellent-sheep", "no-scoreboard")]),
]),
("My first job", "Starting out", [
    ("Learn the three things I'll need tomorrow morning.",
     [("vygotsky", "scaffolding")]),
    ("I just started and I can't do any of it.",
     [("vygotsky", "zpd")]),
    ("I don't know when to ask and when to figure it out.",
     [("vygotsky", "scaffolding")]),
]),
("Should I go back to school", "Starting out", [
    ("When this degree is done, what can I actually do?",
     [("excellent-sheep", "hurdles")]),
    ("Everyone is collecting credentials and I'm panicking.",
     [("dweck", "effect-size")]),
    ("Am I doing this for me or to have an answer ready?",
     [("excellent-sheep", "no-scoreboard"), ("wang-yangming", "innate-knowing")]),
]),
("What I studied doesn't apply", "Starting out", [
    ("It all makes sense until I have to do it.",
     [("wang-yangming", "unity-of-knowing-and-doing"), ("wang-yangming", "polish-on-things")]),
    ("I don't know where to start practicing.",
     [("vygotsky", "zpd")]),
]),

# ── A turn in the road ──
("I lost my job", "A turn in the road", [
    ("Do I need somewhere to live first, or a title first?",
     [("su-shi", "east-slope")]),
    ("Without the title, what do I actually know how to do?",
     [("jung", "the-persona")]),
    ("All those years, gone in one meeting.",
     [("su-shi", "three-exiles")]),
    ("What am I supposed to do now?",
     [("fan-li", "leave-at-the-top")]),
    ("I'm past forty and I don't know what else I can do.",
     [("boyd", "to-be-or-to-do"), ("fan-li", "stock-the-opposite")]),
    ("Without this identity, who am I?",
     [("zhuangzi", "use-of-uselessness")]),
    ("Savings will cover a few more months.",
     [("su-shi", "east-slope")]),
    ("I was laid off and I don't know what to do first.",
     [("su-shi", "east-slope"), ("su-shi", "three-exiles")]),
    ("The position is gone. What is the first thing I do?",
     [("su-shi", "east-slope"), ("su-shi", "three-exiles")]),
]),
("Someone I needed is gone", "A turn in the road", [
    ("Everyone is waiting to see me grieve properly.",
     [("curie", "the-lecture")]),
    ("She's gone. What am I supposed to do tomorrow?",
     [("curie", "the-lecture"), ("cs-lewis", "grief-feels-like-fear")]),
    ("This doesn't feel like sadness. It feels like fear.",
     [("cs-lewis", "grief-feels-like-fear")]),
    ("What held me up my whole life did not hold this time.",
     [("cs-lewis", "house-of-cards"), ("su-shi", "no-wind-no-rain")]),
    ("The harder I try to remember him, the less it's him.",
     [("cs-lewis", "not-replacing-her"), ("huineng", "originally-not-a-thing")]),
    ("I keep thinking there was something I could have done.",
     [("zhuangzi", "equalizing-things")]),
    ("It's been six months and I'm no further along.",
     [("su-shi", "no-wind-no-rain")]),
]),
("Starting over", "A turn in the road", [
    ("Starting from zero at my age — is it too late?",
     [("su-shi", "three-exiles")]),
    ("I'm back at the beginning. What do I do first?",
     [("su-shi", "three-exiles"), ("su-shi", "no-wind-no-rain")]),
]),
("I can't carry it anymore", "A turn in the road", [
    ("The story I told myself stopped holding my weight.",
     [("cs-lewis", "house-of-cards")]),
]),
("Moving somewhere new", "A turn in the road", [
    ("Now that I'm out, I need one small thing to aim at.",
     [("su-shi", "east-slope")]),
    ("New country. What of mine actually came with me?",
     [("granovetter", "weak-ties")]),
    ("New city, and I don't know a soul.",
     [("granovetter", "weak-ties")]),
    ("I moved here and nothing comes to me.",
     [("granovetter", "weak-ties"), ("granovetter", "no-strong-tie-is-a-bridge")]),
    ("My circle is small and I never hear anything new.",
     [("granovetter", "no-strong-tie-is-a-bridge")]),
    ("I moved and left every familiar face behind.",
     [("harvard-study", "social-fitness"), ("granovetter", "weak-ties")]),
    ("I want to move to another country.",
     [("granovetter", "weak-ties"), ("harvard-study", "social-fitness")]),
]),
("Middle of my life", "A turn in the road", [
    ("Is any of what I built still worth something?",
     [("churchill", "sixty-five")]),
    ("Starting over in my forties — is there time?",
     [("jung", "afternoon-of-life")]),
    ("I turned forty and suddenly it feels late.",
     [("jung", "afternoon-of-life")]),
    ("I have everything I was supposed to want and I'm emptier.",
     [("jung", "afternoon-of-life")]),
    ("I've been playing a part for years.",
     [("jung", "the-persona"), ("hochschild", "emotional-labor")]),
    ("The role is gone and I don't know who's left.",
     [("jung", "the-persona")]),
    ("The harder I push the emptier it gets and I don't understand why.",
     [("jung", "afternoon-of-life"), ("zhuangzi", "use-of-uselessness")]),
]),

# ── Nothing's moving ──
("It's already done and I can't undo it", "Nothing's moving", [
    ("It happened. I can't change it.",
     [("su-shi", "no-wind-no-rain")]),
    ("How do I stop running it again?",
     [("huineng", "originally-not-a-thing"), ("zhuangzi", "equalizing-things")]),
    ("It's settled and I'm still fighting it.",
     [("zhuangzi", "equalizing-things"), ("zhuangzi", "ox-carving")]),
]),
("It still hasn't worked", "Nothing's moving", [
    ("I've been saying it for years and nobody listens.",
     [("churchill", "no-one-listened"), ("pu-songling", "forty-years-of-failing")]),
    ("All these years of not making it — did I write any of it down?",
     [("pu-songling", "forty-years-of-failing")]),
    ("I planted it years ago and nothing has come up.",
     [("pu-songling", "forty-years-of-failing")]),
    ("I've been at this for years and it has never worked.",
     [("pu-songling", "forty-years-of-failing")]),
    ("I've taken the exam year after year and never passed.",
     [("pu-songling", "forty-years-of-failing"), ("pu-songling", "collecting-at-the-roadside")]),
    ("I come close every time. I don't know whether to stop.",
     [("pu-songling", "forty-years-of-failing"), ("li-ka-shing", "knowing-when-to-stop")]),
    ('A whole year, and all I have is "still no."',
     [("pu-songling", "forty-years-of-failing"), ("maslach", "three-signs")]),
]),
("They've put me on the shelf", "Nothing's moving", [
    ("Nobody asks my opinion anymore.",
     [("churchill", "wilderness-years"), ("su-shi", "east-slope")]),
    ("I got moved sideways and everybody knows what it means.",
     [("su-shi", "three-exiles")]),
    ("The work they give me matters less every month.",
     [("su-shi", "three-exiles")]),
    ("Do I wait this out or do I go?",
     [("li-ka-shing", "knowing-when-to-stop"), ("fan-li", "leave-at-the-top")]),
]),

# ── Looking back, moving on ──
("The side thing worked, the main thing didn't", "Looking back, moving on", [
    ("The job is flat and the thing I do at night keeps growing.",
     [("pu-songling", "the-side-thing")]),
    ("Should I make the side thing the main thing?",
     [("pu-songling", "the-side-thing"), ("li-ka-shing", "knowing-when-to-stop")]),
    ("What I pushed on went nowhere. What I did casually took off.",
     [("pu-songling", "the-side-thing")]),
    ("I only have scraps of time and I can't afford to quit.",
     [("pu-songling", "collecting-at-the-roadside")]),
]),
("I never put it down", "Looking back, moving on", [
    ("It's been a long time and I'm still not okay.",
     [("curie", "journal-of-grief"), ("cs-lewis", "grief-feels-like-fear")]),
    ("That was years ago and I still can't pick life back up.",
     [("cs-lewis", "grief-feels-like-fear"), ("su-shi", "no-wind-no-rain")]),
    ("So much time has passed and I'm still holding it.",
     [("su-shi", "no-wind-no-rain"), ("huineng", "originally-not-a-thing")]),
    ("The thing I never said is still stuck in my throat.",
     [("thomas-gordon", "i-message")]),
]),
("I don't know what I want", "Looking back, moving on", [
    ("I can't name what I want. I can name what I don't.",
     [("excellent-sheep", "no-scoreboard")]),
    ("I genuinely cannot say what I want.",
     [("zhuangzi", "use-of-uselessness")]),
    ("Who do I want to be in five years?",
     [("wang-yangming", "innate-knowing")]),
    ('The only question I know how to ask is "am I doing well?"',
     [("excellent-sheep", "no-scoreboard"), ("excellent-sheep", "hurdles")]),
]),
("Too many paths", "Looking back, moving on", [
    ("Every option makes sense and I can't choose.",
     [("boyd", "to-be-or-to-do"), ("excellent-sheep", "hurdles")]),
    ("I'm climbing and it isn't the thing I wanted.",
     [("boyd", "to-be-or-to-do"), ("zhuangzi", "use-of-uselessness")]),
    ("What I want to do and what I should do are two different things.",
     [("excellent-sheep", "no-scoreboard")]),
    ("I've done so much and I'm more lost than when I started.",
     [("excellent-sheep", "hurdles"), ("huineng", "originally-not-a-thing")]),
]),
("Do I change direction now", "Looking back, moving on", [
    ("Is switching tracks now too big a risk?",
     [("fan-li", "leave-at-the-top")]),
]),

# ── Things you don't say out loud ──
("I can't stand other people's good news", "Things you don't say out loud", [
    ("My friend is doing well and I feel sick about it.",
     [("zhuangzi", "equalizing-things")]),
    ("Why am I always measuring myself against someone?",
     [("su-shi", "no-bad-people")]),
    ("That kind of person makes my blood go up on sight.",
     [("jung", "the-shadow")]),
]),
("I'm the one who did wrong", "Things you don't say out loud", [
    ("It was my fault and I can't move past it.",
     [("wang-yangming", "bandits-in-the-heart")]),
    ("The more I explain, the worse it gets.",
     [("su-shi", "no-more-writing")]),
]),
("They'll find out I can't do this", "Things you don't say out loud", [
    ("I'm in this seat and I feel hollow in it.",
     [("wang-yangming", "polish-on-things")]),
    ("The fight I'm afraid of is inside me.",
     [("wang-yangming", "bandits-in-the-heart"), ("wang-yangming", "innate-knowing")]),
    ('What I actually want is for someone to say "you were right."',
     [("su-shi", "no-more-writing")]),
]),
("I can't let go of someone", "Things you don't say out loud", [
    ("There are things I only ever wanted to tell him.",
     [("curie", "journal-of-grief"), ("cs-lewis", "not-replacing-her")]),
    ("I'm afraid of forgetting her and afraid what I keep isn't her.",
     [("cs-lewis", "not-replacing-her"), ("huineng", "originally-not-a-thing")]),
    ("I still hate that person.",
     [("wang-yangming", "bandits-in-the-heart")]),
    ("Does forgiving mean admitting I was the problem?",
     [("su-shi", "no-bad-people")]),
    ("It's been years and I still think about him.",
     [("su-shi", "no-wind-no-rain"), ("huineng", "originally-not-a-thing")]),
    ("I delete the number and add it back, over and over.",
     [("wang-yangming", "bandits-in-the-heart")]),
]),
("I've started being afraid of dying", "Things you don't say out loud", [
    ("There's less time left and I haven't done anything.",
     [("su-shi", "no-wind-no-rain")]),
]),
]
